// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-HR5U2DXK.js";
import { className, css, fonts } from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:about-section-2-counter
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mhYWbopcvLHHIXmVUTmg/X0SzP0RSlmV6Eymkeabm/EfDE2Gi4j.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/b1wTl4cxiad8LgrapGvN/naQFf8NwNb4ajY5IR1o8/PsD7rYw_C.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["RoV5qCP9y", "XQVbqgPd3"];
var serializationHash = "framer-wYiis";
var variantClassNames = {
	RoV5qCP9y: "framer-v-n7u2pm",
	XQVbqgPd3: "framer-v-xmzcdr",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "RoV5qCP9y",
	Phone: "XQVbqgPd3",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	bGColor,
	border,
	height,
	id,
	number,
	shadow,
	title,
	width,
	...props
}) => {
	return {
		...props,
		HdJCKG0X0:
			bGColor ??
			props.HdJCKG0X0 ??
			"var(--token-78006fc2-4aed-468c-a9d5-0eb0993d6aea, rgb(201, 224, 242))",
		M5TDTfLVe: number ?? props.M5TDTfLVe ?? "2018",
		NodRT1TQI: border ??
			props.NodRT1TQI ?? {
				borderColor:
					'var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178)) /* {"name":"5488B2"} */',
				borderStyle: "solid",
				borderWidth: 1,
			},
		S8HsXQb5x:
			title ?? props.S8HsXQb5x ?? "The year we started, with 6 learners",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RoV5qCP9y",
		w7DvNUrxX:
			shadow ??
			props.w7DvNUrxX ??
			"4px 4px 0px 0px var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		M5TDTfLVe: M5TDTfLVe2,
		S8HsXQb5x: S8HsXQb5x2,
		HdJCKG0X0: HdJCKG0X02,
		NodRT1TQI: NodRT1TQI2,
		w7DvNUrxX: w7DvNUrxX2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RoV5qCP9y",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-n7u2pm",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"RoV5qCP9y"}
						ref={refBinding}
						style={{
							"--1e12pfm": w7DvNUrxX2,
							"--border-bottom-width":
								(NodRT1TQI2?.borderBottomWidth ?? NodRT1TQI2?.borderWidth) +
								"px",
							"--border-color": NodRT1TQI2?.borderColor,
							"--border-left-width":
								(NodRT1TQI2?.borderLeftWidth ?? NodRT1TQI2?.borderWidth) + "px",
							"--border-right-width":
								(NodRT1TQI2?.borderRightWidth ?? NodRT1TQI2?.borderWidth) +
								"px",
							"--border-style": NodRT1TQI2?.borderStyle,
							"--border-top-width":
								(NodRT1TQI2?.borderTopWidth ?? NodRT1TQI2?.borderWidth) + "px",
							backgroundColor: HdJCKG0X02,
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "var(--1e12pfm)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								XQVbqgPd3: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-1j36jek"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"eZWPYb0G8"}
							style={{
								"--extracted-1of0zx5":
									"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={M5TDTfLVe2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h2
									suppressHydrationWarning={true}
									className={"framer-styles-preset-1cm76ll"}
									data-styles-preset={"XA1CONPGx"}
									dir={"auto"}
									style={{
										"--framer-text-alignment": "start",
										"--framer-text-color":
											"var(--extracted-1of0zx5, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
									}}
								>
									{"2018"}
								</motion.h2>
							</React.Fragment>
						</RichText>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1u1o857"}
							data-framer-name={"Border"}
							layoutDependency={layoutDependency}
							layoutId={"K_wXLt_7f"}
							style={{
								backgroundColor:
									"var(--token-dbb48573-48d8-403f-ad86-7009a5265b2f, rgba(20, 38, 29, 0.2))",
							}}
						/>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-17g4076"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"JUmweHTCZ"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-e7e6c389-54de-40d3-bd41-8072dc4a41a5, rgb(69, 86, 75))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={S8HsXQb5x2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									suppressHydrationWarning={true}
									className={"framer-styles-preset-7580yq"}
									data-styles-preset={"ESdyUGyJl"}
									dir={"auto"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-e7e6c389-54de-40d3-bd41-8072dc4a41a5, rgb(69, 86, 75)))",
									}}
								>
									{"The year we started, with 6 learners"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	".framer-wYiis.framer-1kgtn9x, .framer-wYiis .framer-1kgtn9x { display: block; }",
	".framer-wYiis.framer-n7u2pm { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 30px; position: relative; width: 400px; will-change: var(--framer-will-change-override, transform); }",
	".framer-wYiis .framer-1j36jek, .framer-wYiis .framer-17g4076 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-wYiis .framer-1u1o857 { flex: none; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-wYiis.framer-v-xmzcdr.framer-n7u2pm { gap: 10px; padding: 20px; width: 390px; }",
	...css2,
	...css,
	'.framer-wYiis[data-border="true"]::after, .framer-wYiis [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerPsD7rYw_C = withCSS(Component, css3, "framer-wYiis");
var stdin_default = FramerPsD7rYw_C;
FramerPsD7rYw_C.displayName = "Achievement Card";
FramerPsD7rYw_C.defaultProps = {
	height: 166,
	width: 400,
};
addPropertyControls(FramerPsD7rYw_C, {
	variant: {
		options: ["RoV5qCP9y", "XQVbqgPd3"],
		optionTitles: ["Default", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	M5TDTfLVe: {
		defaultValue: "2018",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	onM5TDTfLVeChange: {
		changes: "M5TDTfLVe",
		type: ControlType.ChangeHandler,
	},
	S8HsXQb5x: {
		defaultValue: "The year we started, with 6 learners",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	onS8HsXQb5xChange: {
		changes: "S8HsXQb5x",
		type: ControlType.ChangeHandler,
	},
	HdJCKG0X0: {
		defaultValue:
			'var(--token-78006fc2-4aed-468c-a9d5-0eb0993d6aea, rgb(201, 224, 242)) /* {"name":"Blue_bg"} */',
		title: "BG Color",
		type: ControlType.Color,
	},
	NodRT1TQI: {
		defaultValue: {
			borderColor:
				'var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178)) /* {"name":"5488B2"} */',
			borderStyle: "solid",
			borderWidth: 1,
		},
		title: "Border",
		type: ControlType.Border,
	},
	w7DvNUrxX: {
		defaultValue: [
			{
				blur: 0,
				color:
					'var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178)) /* {"name":"5488B2"} */',
				diffusion: 0.5,
				focus: 0.5,
				inset: false,
				spread: 0,
				type: "box",
				x: 4,
				y: 4,
			},
		],
		title: "Shadow",
		type: ControlType.BoxShadow,
	},
});
addFonts(
	FramerPsD7rYw_C,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/mhYWbopcvLHHIXmVUTmg/X0SzP0RSlmV6Eymkeabm/EfDE2Gi4j.js
var AchievementCardFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder2 = ["NNKt0lyBm", "ahpGtVPuS", "V9_KirOdP"];
var serializationHash2 = "framer-HsaQD";
var variantClassNames2 = {
	ahpGtVPuS: "framer-v-l1ux3s",
	NNKt0lyBm: "framer-v-1j5mhnw",
	V9_KirOdP: "framer-v-dr4zuh",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transition3 = {
	delay: 0.35,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var transition4 = {
	delay: 0.5,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 30,
};
var transition5 = {
	delay: 0.65,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 30,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	Desktop: "NNKt0lyBm",
	Phone: "V9_KirOdP",
	Tablet: "ahpGtVPuS",
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "NNKt0lyBm",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "NNKt0lyBm",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants2
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition2 suppressHydrationWarning={true} value={transition12}>
					<motion2.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1j5mhnw",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"NNKt0lyBm"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								ahpGtVPuS: {
									"data-framer-name": "Tablet",
								},
								V9_KirOdP: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.section
							suppressHydrationWarning={true}
							className={"framer-scq1s3"}
							data-framer-name={"Counter"}
							layoutDependency={layoutDependency}
							layoutId={"Lip5dGqbM"}
						>
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-1fqcske"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"J7tfQllPJ"}
							>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-yookyw"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"pP13uoagj"}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={166}
										width={`max((min(${componentViewport?.width || "100vw"}, 1460px) - 150px) / 4, 50px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											0 +
											150 +
											0 +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												ahpGtVPuS: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														100 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												V9_KirOdP: {
													width: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 60px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														80 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											suppressHydrationWarning={true}
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__exit={animation1}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1508lk7-container"}
											layoutDependency={layoutDependency}
											layoutId={"MistmsK6F-container"}
											nodeId={"MistmsK6F"}
											rendersWithMotion={true}
											scopeId={"EfDE2Gi4j"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												HdJCKG0X0:
													"var(--token-78006fc2-4aed-468c-a9d5-0eb0993d6aea, rgb(201, 224, 242))",
												height: "100%",
												id: "MistmsK6F",
												layoutId: "MistmsK6F",
												M5TDTfLVe: "2018",
												NodRT1TQI: {
													borderColor:
														"var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178))",
													borderStyle: "solid",
													borderWidth: 1,
												},
												S8HsXQb5x: "Started with 6 learners",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: matchVariant("RoV5qCP9y"),
												w7DvNUrxX:
													"4px 4px 0px 0px var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178))",
												width: "100%",
												...addPropertyOverrides2(
													{
														ahpGtVPuS: {
															variant: matchVariant("XQVbqgPd3"),
														},
														V9_KirOdP: {
															variant: matchVariant("XQVbqgPd3"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={166}
										width={`max((min(${componentViewport?.width || "100vw"}, 1460px) - 150px) / 4, 50px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											0 +
											150 +
											0 +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												ahpGtVPuS: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														100 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												V9_KirOdP: {
													width: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 60px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														80 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											suppressHydrationWarning={true}
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__exit={animation2}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-rx0w1r-container"}
											layoutDependency={layoutDependency}
											layoutId={"LSTkTVxQr-container"}
											nodeId={"LSTkTVxQr"}
											rendersWithMotion={true}
											scopeId={"EfDE2Gi4j"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												HdJCKG0X0:
													"var(--token-e8cec243-b334-4568-a85b-a75cea534593, rgb(214, 229, 154))",
												height: "100%",
												id: "LSTkTVxQr",
												layoutId: "LSTkTVxQr",
												M5TDTfLVe: "900+",
												NodRT1TQI: {
													borderColor:
														"var(--token-5bafd284-4248-4179-8fdd-7a454d5f3ef0, rgb(160, 175, 100))",
													borderStyle: "solid",
													borderWidth: 1,
												},
												S8HsXQb5x: "Learners taught since",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: matchVariant("RoV5qCP9y"),
												w7DvNUrxX:
													"4px 4px 0px 0px var(--token-5bafd284-4248-4179-8fdd-7a454d5f3ef0, rgb(160, 175, 100))",
												width: "100%",
												...addPropertyOverrides2(
													{
														ahpGtVPuS: {
															variant: matchVariant("XQVbqgPd3"),
														},
														V9_KirOdP: {
															variant: matchVariant("XQVbqgPd3"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={166}
										width={`max((min(${componentViewport?.width || "100vw"}, 1460px) - 150px) / 4, 50px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											0 +
											150 +
											0 +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												ahpGtVPuS: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														100 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												V9_KirOdP: {
													width: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 60px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														80 +
														0 +
														0 +
														0 +
														0 +
														186,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											suppressHydrationWarning={true}
											__framer__animate={{
												transition: transition4,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__exit={animation3}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1yq4z0w-container"}
											layoutDependency={layoutDependency}
											layoutId={"oG0K4wWxS-container"}
											nodeId={"oG0K4wWxS"}
											rendersWithMotion={true}
											scopeId={"EfDE2Gi4j"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												HdJCKG0X0:
													"var(--token-d0e4cb96-2373-4292-a52b-0c70e08d9898, rgb(246, 215, 232))",
												height: "100%",
												id: "oG0K4wWxS",
												layoutId: "oG0K4wWxS",
												M5TDTfLVe: "24",
												NodRT1TQI: {
													borderColor:
														"var(--token-1155d13b-37e2-47ed-93ce-c08c2cfdd816, rgb(190, 143, 169))",
													borderStyle: "solid",
													borderWidth: 1,
												},
												S8HsXQb5x: "Mentors on the team",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: matchVariant("RoV5qCP9y"),
												w7DvNUrxX:
													"4px 4px 0px 0px var(--token-1155d13b-37e2-47ed-93ce-c08c2cfdd816, rgb(190, 143, 169))",
												width: "100%",
												...addPropertyOverrides2(
													{
														ahpGtVPuS: {
															variant: matchVariant("XQVbqgPd3"),
														},
														V9_KirOdP: {
															variant: matchVariant("XQVbqgPd3"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={166}
										width={`max((min(${componentViewport?.width || "100vw"}, 1460px) - 150px) / 4, 50px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											0 +
											150 +
											0 +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												ahpGtVPuS: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														100 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												V9_KirOdP: {
													width: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 60px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														80 +
														0 +
														0 +
														0 +
														0 +
														186,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											suppressHydrationWarning={true}
											__framer__animate={{
												transition: transition5,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__exit={animation4}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-n27idi-container"}
											layoutDependency={layoutDependency}
											layoutId={"PLWncQXYA-container"}
											nodeId={"PLWncQXYA"}
											rendersWithMotion={true}
											scopeId={"EfDE2Gi4j"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												HdJCKG0X0:
													"var(--token-9f7780f5-af12-4101-9125-2580d35c4118, rgb(249, 216, 192))",
												height: "100%",
												id: "PLWncQXYA",
												layoutId: "PLWncQXYA",
												M5TDTfLVe: "4.9",
												NodRT1TQI: {
													borderColor:
														"var(--token-a059f435-bb0e-48c5-ac68-2aad5474e6d7, rgb(186, 146, 117))",
													borderStyle: "solid",
													borderWidth: 1,
												},
												S8HsXQb5x: "Rating across 300+ reviews",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: matchVariant("RoV5qCP9y"),
												w7DvNUrxX:
													"4px 4px 0px 0px var(--token-a059f435-bb0e-48c5-ac68-2aad5474e6d7, rgb(186, 146, 117))",
												width: "100%",
												...addPropertyOverrides2(
													{
														ahpGtVPuS: {
															variant: matchVariant("XQVbqgPd3"),
														},
														V9_KirOdP: {
															variant: matchVariant("XQVbqgPd3"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
								</motion2.div>
							</motion2.div>
						</motion2.section>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	".framer-HsaQD.framer-cj9eav, .framer-HsaQD .framer-cj9eav { display: block; }",
	".framer-HsaQD.framer-1j5mhnw { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-HsaQD .framer-scq1s3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 150px 0px 150px 0px; position: relative; width: 100%; }",
	".framer-HsaQD .framer-1fqcske { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-HsaQD .framer-yookyw { display: grid; flex: none; gap: 30px 30px; grid-auto-rows: min-content; grid-template-columns: repeat(4, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-HsaQD .framer-1508lk7-container, .framer-HsaQD .framer-rx0w1r-container, .framer-HsaQD .framer-1yq4z0w-container, .framer-HsaQD .framer-n27idi-container { align-self: start; flex: none; height: 100%; justify-self: start; position: relative; width: 100%; }",
	".framer-HsaQD.framer-v-l1ux3s.framer-1j5mhnw { width: 810px; }",
	".framer-HsaQD.framer-v-l1ux3s .framer-scq1s3 { padding: 100px 0px 100px 0px; }",
	".framer-HsaQD.framer-v-dr4zuh.framer-1j5mhnw { width: 390px; }",
	".framer-HsaQD.framer-v-dr4zuh .framer-scq1s3 { padding: 80px 0px 80px 0px; }",
	".framer-HsaQD.framer-v-dr4zuh .framer-1fqcske { padding: 0px 20px 0px 20px; }",
	".framer-HsaQD.framer-v-dr4zuh .framer-yookyw { gap: 20px; grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
];
var FramerEfDE2Gi4j = withCSS2(Component2, css4, "framer-HsaQD");
var stdin_default2 = FramerEfDE2Gi4j;
FramerEfDE2Gi4j.displayName = "About Section 2 \u2014 Counter";
FramerEfDE2Gi4j.defaultProps = {
	height: 466,
	width: 1200,
};
addPropertyControls2(FramerEfDE2Gi4j, {
	variant: {
		options: ["NNKt0lyBm", "ahpGtVPuS", "V9_KirOdP"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerEfDE2Gi4j,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AchievementCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerEfDE2Gi4j.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:about-section-2-counter
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutSection2CounterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var about_section_2_counter_default = ComponentWithRoot;
export { about_section_2_counter_default as default };
