// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EPDNPLDL.js";
import { stdin_default } from "./chunks/chunk-UR7P3ULX.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-FUMATQXC.js";
import { className, css, fonts } from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:about-section-4-online
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/eJNTuQkXvokSKImHB3pQ/NWf5y4JuzyswbpE1T05c/OuCPWG0MS.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var PreTitleFonts = getFonts(stdin_default2);
var BadgeFonts = getFonts(stdin_default);
var cycleOrder = ["gd3l2CGiS", "ALUhDzZMp", "JrTa9IUi7"];
var serializationHash = "framer-sMTLA";
var variantClassNames = {
	ALUhDzZMp: "framer-v-bg0ilf",
	gd3l2CGiS: "framer-v-106x16a",
	JrTa9IUi7: "framer-v-i94h85",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var transition3 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "gd3l2CGiS",
	Phone: "JrTa9IUi7",
	Tablet: "ALUhDzZMp",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "gd3l2CGiS",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "gd3l2CGiS",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-106x16a",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"gd3l2CGiS"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								ALUhDzZMp: {
									"data-framer-name": "Tablet",
								},
								JrTa9IUi7: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-1dw3n43"}
							data-framer-name={"Online"}
							layoutDependency={layoutDependency}
							layoutId={"O1ueBye15"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-culz1z"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"EwJmCKUca"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1ojombb"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"d2RftL01O"}
								>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1r8onhx"}
										data-framer-name={"Left"}
										layoutDependency={layoutDependency}
										layoutId={"eMEiVocdI"}
									>
										<Image1
											suppressHydrationWarning={true}
											background={{
												alt: "Counter single image",
												fit: "fill",
												intrinsicHeight: 616,
												intrinsicWidth: 800,
												pixelHeight: 616,
												pixelWidth: 800,
												sizes: `calc(max((min(${componentViewport?.width || "100vw"}, 1460px) - 700px) / 9, 50px) * 4 + 240px)`,
												src: "https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?width=800&height=616",
												srcSet:
													"https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?scale-down-to=512&width=800&height=616 512w,https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?width=800&height=616 800w",
											}}
											className={"framer-9h8irw"}
											layoutDependency={layoutDependency}
											layoutId={"gr9sZmpeo"}
											style={{
												borderBottomLeftRadius: 20,
												borderBottomRightRadius: 20,
												borderTopLeftRadius: 20,
												borderTopRightRadius: 20,
											}}
											{...addPropertyOverrides(
												{
													ALUhDzZMp: {
														background: {
															alt: "Counter single image",
															fit: "fill",
															intrinsicHeight: 616,
															intrinsicWidth: 800,
															pixelHeight: 616,
															pixelWidth: 800,
															sizes: `calc(max((min(${componentViewport?.width || "100vw"}, 1460px) - 180px) / 5, 50px) * 2 + 30px)`,
															src: "https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?width=800&height=616",
															srcSet:
																"https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?scale-down-to=512&width=800&height=616 512w,https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?width=800&height=616 800w",
														},
													},
													JrTa9IUi7: {
														background: {
															alt: "Counter single image",
															fit: "fill",
															intrinsicHeight: 616,
															intrinsicWidth: 800,
															pixelHeight: 616,
															pixelWidth: 800,
															sizes: `max(min(${componentViewport?.width || "100vw"}, 1460px) - 40px, 50px)`,
															src: "https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?width=800&height=616",
															srcSet:
																"https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?scale-down-to=512&width=800&height=616 512w,https://framerusercontent.com/images/zkeQsPolMXishLm6DHO92DjwGQ.jpg?width=800&height=616 800w",
														},
														fitImageDimension: "height",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</MotionDivWithFX>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition3,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1gqu5dq"}
										data-framer-name={"Right"}
										layoutDependency={layoutDependency}
										layoutId={"M0Igl58om"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-83t744"}
											data-framer-name={"Heading"}
											layoutDependency={layoutDependency}
											layoutId={"y_bfUpbHx"}
										>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1uocsi3"}
												data-framer-name={"Content"}
												layoutDependency={layoutDependency}
												layoutId={"NCFNw0QVM"}
											>
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={34}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-b3p9p1-container"}
														layoutDependency={layoutDependency}
														layoutId={"zlgYon48f-container"}
														nodeId={"zlgYon48f"}
														rendersWithMotion={true}
														scopeId={"OuCPWG0MS"}
													>
														{_jsx(stdin_default2, {
															suppressHydrationWarning: true,
															height: "100%",
															HJ8LmVVDm:
																"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
															id: "zlgYon48f",
															layoutId: "zlgYon48f",
															qzeUwXZ6t:
																"var(--token-9be2179a-d4c3-4b1c-a57e-66ad0ebb844d, rgb(232, 114, 44))",
															wCKXxEnrH: "In-center & online",
															width: "100%",
															ZFJwwHvsK:
																"var(--token-d0e4cb96-2373-4292-a52b-0c70e08d9898, rgb(246, 215, 232))",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
												<motion.div
													suppressHydrationWarning={true}
													className={"framer-302c1b"}
													data-framer-name={"Heading"}
													layoutDependency={layoutDependency}
													layoutId={"AEvm7Yunl"}
												>
													<RichText
														suppressHydrationWarning={true}
														__fromCanvasComponent={true}
														className={"framer-arf4n0"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"zvS3QdyRU"}
														style={{
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h2
																suppressHydrationWarning={true}
																className={"framer-styles-preset-jcbbly"}
																data-styles-preset={"UXoQEMm1m"}
																dir={"auto"}
															>
																{"Learn"}
															</motion.h2>
														</React.Fragment>
													</RichText>
													<RichText
														suppressHydrationWarning={true}
														__fromCanvasComponent={true}
														className={"framer-o39ifm"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"RIiIG_DEn"}
														style={{
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h2
																suppressHydrationWarning={true}
																className={"framer-styles-preset-jcbbly"}
																data-styles-preset={"UXoQEMm1m"}
																dir={"auto"}
															>
																{"where"}
															</motion.h2>
														</React.Fragment>
													</RichText>
													<RichText
														suppressHydrationWarning={true}
														__fromCanvasComponent={true}
														className={"framer-ceqi6x"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"JpdWDE_3d"}
														style={{
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h2
																suppressHydrationWarning={true}
																className={"framer-styles-preset-jcbbly"}
																data-styles-preset={"UXoQEMm1m"}
																dir={"auto"}
															>
																{"you"}
															</motion.h2>
														</React.Fragment>
													</RichText>
													<motion.div
														suppressHydrationWarning={true}
														className={"framer-gfd225"}
														data-framer-name={"Highlight"}
														layoutDependency={layoutDependency}
														layoutId={"JSRQ73Fvy"}
													>
														<RichText
															suppressHydrationWarning={true}
															__fromCanvasComponent={true}
															className={"framer-kkp75x"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"JGBbctpBG"}
															style={{
																"--extracted-1of0zx5":
																	"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
																rotate: 5,
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.h2
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-jcbbly"}
																	data-styles-preset={"UXoQEMm1m"}
																	dir={"auto"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-1of0zx5, var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100)))",
																	}}
																>
																	{"learn best"}
																</motion.h2>
															</React.Fragment>
														</RichText>
														<Image1
															suppressHydrationWarning={true}
															background={{
																alt: "",
																fit: "fill",
																intrinsicHeight: 34,
																intrinsicWidth: 33,
																pixelHeight: 34,
																pixelWidth: 33,
																sizes: "32px",
																src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
															}}
															className={"framer-bwaajz"}
															data-framer-name={"Top Decor"}
															layoutDependency={layoutDependency}
															layoutId={"tOnnk7VSW"}
														/>
														<Image1
															suppressHydrationWarning={true}
															background={{
																alt: "",
																fit: "stretch",
																intrinsicHeight: 46,
																intrinsicWidth: 219,
																pixelHeight: 46,
																pixelWidth: 219,
																positionX: "center",
																positionY: "center",
																src: "https://framerusercontent.com/images/JrJVDghR4XSfM4fEkVG4YlBTu0E.svg?width=219&height=46",
															}}
															className={"framer-1842n1j"}
															data-framer-name={"Bottom Decor"}
															layoutDependency={layoutDependency}
															layoutId={"n169zAIHk"}
														/>
													</motion.div>
												</motion.div>
											</motion.div>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-2hopel"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"SWTDGr4Eb"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-7580yq"}
														data-styles-preset={"ESdyUGyJl"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "start",
														}}
													>
														{
															"Drop in at our center, or join live from home, same mentors, same materials, same progress reports every month."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-ywb6jy"}
											data-framer-name={"Badges"}
											layoutDependency={layoutDependency}
											layoutId={"V2kLBs5oD"}
										>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={38}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-9qze3w-container"}
													layoutDependency={layoutDependency}
													layoutId={"X3iLgWaKm-container"}
													nodeId={"X3iLgWaKm"}
													rendersWithMotion={true}
													scopeId={"OuCPWG0MS"}
												>
													{_jsx(stdin_default, {
														suppressHydrationWarning: true,
														FVqKgjdnA:
															"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
														height: "100%",
														id: "X3iLgWaKm",
														layoutId: "X3iLgWaKm",
														NTl8xZNe6: "After-school slots",
														variant: matchVariant("Y0s5tgNrT"),
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={38}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-146iok9-container"}
													layoutDependency={layoutDependency}
													layoutId={"pTJt4cyuV-container"}
													nodeId={"pTJt4cyuV"}
													rendersWithMotion={true}
													scopeId={"OuCPWG0MS"}
												>
													{_jsx(stdin_default, {
														suppressHydrationWarning: true,
														FVqKgjdnA:
															"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
														height: "100%",
														id: "pTJt4cyuV",
														layoutId: "pTJt4cyuV",
														NTl8xZNe6: "Weekend groups",
														variant: matchVariant("Y0s5tgNrT"),
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={38}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-fqmly9-container"}
													layoutDependency={layoutDependency}
													layoutId={"IYI9EPBfJ-container"}
													nodeId={"IYI9EPBfJ"}
													rendersWithMotion={true}
													scopeId={"OuCPWG0MS"}
												>
													{_jsx(stdin_default, {
														suppressHydrationWarning: true,
														FVqKgjdnA:
															"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
														height: "100%",
														id: "IYI9EPBfJ",
														layoutId: "IYI9EPBfJ",
														NTl8xZNe6: "Live online",
														variant: matchVariant("Y0s5tgNrT"),
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={38}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-n6ksxd-container"}
													layoutDependency={layoutDependency}
													layoutId={"MAbi2GUvz-container"}
													nodeId={"MAbi2GUvz"}
													rendersWithMotion={true}
													scopeId={"OuCPWG0MS"}
												>
													{_jsx(stdin_default, {
														suppressHydrationWarning: true,
														FVqKgjdnA:
															"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
														height: "100%",
														id: "MAbi2GUvz",
														layoutId: "MAbi2GUvz",
														NTl8xZNe6: "Homework help",
														variant: matchVariant("Y0s5tgNrT"),
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</motion.div>
									</MotionDivWithFX>
								</motion.div>
							</motion.div>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	".framer-sMTLA.framer-1cj22bh, .framer-sMTLA .framer-1cj22bh { display: block; }",
	".framer-sMTLA.framer-106x16a { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-sMTLA .framer-1dw3n43 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 150px 0px 150px 0px; position: relative; width: 100%; }",
	".framer-sMTLA .framer-culz1z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-sMTLA .framer-1ojombb { display: grid; flex: none; gap: 80px; grid-auto-rows: min-content; grid-template-columns: repeat(9, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sMTLA .framer-1r8onhx { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; grid-column: span 4; height: 100%; justify-content: flex-start; justify-self: start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-sMTLA .framer-9h8irw { flex: 1 0 0px; gap: 0px; height: 1px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-sMTLA .framer-1gqu5dq { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; grid-column: span 5; height: 100%; justify-content: flex-start; justify-self: start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-sMTLA .framer-83t744 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sMTLA .framer-1uocsi3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sMTLA .framer-b3p9p1-container, .framer-sMTLA .framer-9qze3w-container, .framer-sMTLA .framer-146iok9-container, .framer-sMTLA .framer-fqmly9-container, .framer-sMTLA .framer-n6ksxd-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-sMTLA .framer-302c1b { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sMTLA .framer-arf4n0, .framer-sMTLA .framer-o39ifm, .framer-sMTLA .framer-ceqi6x, .framer-sMTLA .framer-kkp75x { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-sMTLA .framer-gfd225 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 26px 0px; position: relative; width: min-content; }",
	".framer-sMTLA .framer-bwaajz { -webkit-user-select: none; aspect-ratio: 1 / 1; flex: none; height: auto; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 32px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-sMTLA .framer-1842n1j { -webkit-user-select: none; bottom: 0px; flex: none; height: 44px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-sMTLA .framer-2hopel { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-sMTLA .framer-ywb6jy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 10px 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-sMTLA.framer-v-bg0ilf.framer-106x16a { width: 810px; }",
	".framer-sMTLA.framer-v-bg0ilf .framer-1dw3n43 { padding: 100px 0px 100px 0px; }",
	".framer-sMTLA.framer-v-bg0ilf .framer-1ojombb { gap: 30px; grid-template-columns: repeat(5, minmax(50px, 1fr)); }",
	".framer-sMTLA.framer-v-bg0ilf .framer-1r8onhx { grid-column: span 2; }",
	".framer-sMTLA.framer-v-bg0ilf .framer-1gqu5dq { gap: 30px; grid-column: span 3; }",
	".framer-sMTLA.framer-v-bg0ilf .framer-83t744, .framer-sMTLA.framer-v-i94h85 .framer-83t744 { gap: 10px; }",
	".framer-sMTLA.framer-v-bg0ilf .framer-302c1b { gap: 0px 10px; }",
	".framer-sMTLA.framer-v-i94h85.framer-106x16a { width: 390px; }",
	".framer-sMTLA.framer-v-i94h85 .framer-1dw3n43 { padding: 80px 0px 80px 0px; }",
	".framer-sMTLA.framer-v-i94h85 .framer-culz1z { padding: 0px 20px 0px 20px; }",
	".framer-sMTLA.framer-v-i94h85 .framer-1ojombb { gap: 30px; grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	".framer-sMTLA.framer-v-i94h85 .framer-1r8onhx { grid-column: span 1; }",
	".framer-sMTLA.framer-v-i94h85 .framer-9h8irw { flex: none; height: auto; }",
	".framer-sMTLA.framer-v-i94h85 .framer-1gqu5dq { gap: 30px; grid-column: span 1; }",
	".framer-sMTLA.framer-v-i94h85 .framer-302c1b { gap: 0px 8px; }",
	...css2,
	...css,
];
var FramerOuCPWG0MS = withCSS(Component, css3, "framer-sMTLA");
var stdin_default3 = FramerOuCPWG0MS;
FramerOuCPWG0MS.displayName = "About Section 4 \u2014 Online";
FramerOuCPWG0MS.defaultProps = {
	height: 738,
	width: 1200,
};
addPropertyControls(FramerOuCPWG0MS, {
	variant: {
		options: ["gd3l2CGiS", "ALUhDzZMp", "JrTa9IUi7"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerOuCPWG0MS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PreTitleFonts,
		...BadgeFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerOuCPWG0MS.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:about-section-4-online
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutSection4OnlineFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var about_section_4_online_default = ComponentWithRoot;
export { about_section_4_online_default as default };
