// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * title?: string // Title
 * onT2OJLVTSbChange?: any // onT2OJLVTSbChange
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-AOWK4JFD.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-AVXJV35N.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-FUMATQXC.js";
import { stdin_default } from "./chunks/chunk-DPP5EL47.js";
import "./chunks/chunk-C742CGXR.js";
import { className, css, fonts } from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:cta-mentor
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7make7SL4ifR0wIvWgTh/K2RiJmEBKb9phfEsC5V4/S3G1yu2Yh.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PreTitleFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var MotionDivWithFX = withFX(motion.div);
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = ["i4bpSSNVm", "hskaPnjRh", "QGilQypG9"];
var serializationHash = "framer-fLY7v";
var variantClassNames = {
	hskaPnjRh: "framer-v-1igazh3",
	i4bpSSNVm: "framer-v-1gxhp5z",
	QGilQypG9: "framer-v-bvrs6s",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var transition3 = {
	delay: 0.3,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var transition4 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 30,
};
var transition5 = {
	delay: 0.6,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 30,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "i4bpSSNVm",
	Phone: "QGilQypG9",
	Tablet: "hskaPnjRh",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		T2OJLVTsb: title ?? props.T2OJLVTsb ?? "",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "i4bpSSNVm",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		T2OJLVTsb: T2OJLVTsb2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "i4bpSSNVm",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(T2OJLVTsb2);
	const router = useRouter();
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.section
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1gxhp5z",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"i4bpSSNVm"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-9f7780f5-af12-4101-9125-2580d35c4118, rgb(249, 216, 192))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								hskaPnjRh: {
									"data-framer-name": "Tablet",
								},
								QGilQypG9: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-18nf041"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"NjGxluLEF"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-xy79ny"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"dLvi3Zajg"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-19o8lku"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"CUX0S8G3D"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1qg7ern"}
										data-framer-name={"Heading"}
										layoutDependency={layoutDependency}
										layoutId={"lv0PDWb7C"}
									>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={34}
										>
											<SmartComponentScopedContainerWithFX
												suppressHydrationWarning={true}
												__framer__animate={{
													transition: transition2,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__exit={animation1}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-u8h2tx-container"}
												layoutDependency={layoutDependency}
												layoutId={"GnjRbwUFw-container"}
												nodeId={"GnjRbwUFw"}
												rendersWithMotion={true}
												scopeId={"S3G1yu2Yh"}
											>
												{_jsx(stdin_default2, {
													suppressHydrationWarning: true,
													height: "100%",
													HJ8LmVVDm:
														"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
													id: "GnjRbwUFw",
													layoutId: "GnjRbwUFw",
													qzeUwXZ6t:
														"var(--token-9be2179a-d4c3-4b1c-a57e-66ad0ebb844d, rgb(232, 114, 44))",
													wCKXxEnrH: "Free intro session",
													width: "100%",
													ZFJwwHvsK:
														"var(--token-d0e4cb96-2373-4292-a52b-0c70e08d9898, rgb(246, 215, 232))",
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<MotionDivWithFX
											suppressHydrationWarning={true}
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__exit={animation2}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1xtf8ag"}
											data-framer-name={"Heading"}
											layoutDependency={layoutDependency}
											layoutId={"yTppCmxVM"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-5y94iv"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"RD_ukoIsC"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-o3myil"}
														data-styles-preset={"aKvt8sYYy"}
														dir={"auto"}
													>
														{"Meet"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											{visible !== false && (
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-12k8zzo"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"l3CSDoXVv"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													text={T2OJLVTsb2}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.h2
															suppressHydrationWarning={true}
															className={"framer-styles-preset-o3myil"}
															data-styles-preset={"aKvt8sYYy"}
															dir={"auto"}
														>
															{"Maya"}
														</motion.h2>
													</React.Fragment>
												</RichText>
											)}
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-xzurxb"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"xkJS61U6H"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-o3myil"}
														data-styles-preset={"aKvt8sYYy"}
														dir={"auto"}
													>
														{"for"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1b2evln"}
												data-framer-name={"Highlight"}
												layoutDependency={layoutDependency}
												layoutId={"G1pw_LHv8"}
											>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-8uvcru"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"iozUL5MIt"}
													style={{
														"--extracted-1of0zx5":
															"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
														rotate: 5,
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.h2
															suppressHydrationWarning={true}
															className={"framer-styles-preset-o3myil"}
															data-styles-preset={"aKvt8sYYy"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100)))",
															}}
														>
															{"free"}
														</motion.h2>
													</React.Fragment>
												</RichText>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 34,
														intrinsicWidth: 33,
														pixelHeight: 34,
														pixelWidth: 33,
														sizes: "32px",
														src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
													}}
													className={"framer-1f6v95z"}
													data-framer-name={"Top Decor"}
													layoutDependency={layoutDependency}
													layoutId={"QLhRx3fPB"}
												/>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "stretch",
														intrinsicHeight: 46,
														intrinsicWidth: 219,
														pixelHeight: 46,
														pixelWidth: 219,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/JrJVDghR4XSfM4fEkVG4YlBTu0E.svg?width=219&height=46",
													}}
													className={"framer-8jpqwa"}
													data-framer-name={"Bottom Decor"}
													layoutDependency={layoutDependency}
													layoutId={"tFrPupZ9B"}
												/>
											</motion.div>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-28n2wi"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Ha4wBQlBD"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-o3myil"}
														data-styles-preset={"aKvt8sYYy"}
														dir={"auto"}
													>
														{"anytime"}
													</motion.h2>
												</React.Fragment>
											</RichText>
										</MotionDivWithFX>
									</motion.div>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation3}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-vhve7i"}
										data-framer-name={"Description"}
										layoutDependency={layoutDependency}
										layoutId={"KhQo3rdFz"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-eic37t"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"pWAmtp98d"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-7580yq"}
													data-styles-preset={"ESdyUGyJl"}
													dir={"auto"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{
														"Your first session is completely free,  No hidden fees, no pressure, no strings attached. Walk away with a personalised learning plan built around your child's goals and learning style."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</MotionDivWithFX>
								</motion.div>
								<MotionDivWithFX
									suppressHydrationWarning={true}
									__framer__animate={{
										transition: transition5,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation4}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-6u7ipj"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"cbMt6g7hm"}
									style={{
										backgroundColor:
											"var(--token-a225ace6-638e-469b-9793-3ab54fcf3b3a, rgb(27, 52, 40))",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-i9vv7s"}
										data-framer-name={"Left"}
										layoutDependency={layoutDependency}
										layoutId={"umMF1iqv3"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1hrmsmn"}
											data-framer-name={"Left"}
											layoutDependency={layoutDependency}
											layoutId={"LdY00nhjI"}
										>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-l61qnx"}
												data-framer-name={"Icon"}
												layoutDependency={layoutDependency}
												layoutId={"jLBfGuZ3r"}
												style={{
													backgroundColor:
														"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
													borderBottomLeftRadius: "50%",
													borderBottomRightRadius: "50%",
													borderTopLeftRadius: "50%",
													borderTopRightRadius: "50%",
												}}
											>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fit",
														intrinsicHeight: 28,
														intrinsicWidth: 28,
														pixelHeight: 28,
														pixelWidth: 28,
														positionX: "center",
														positionY: "center",
														sizes: "28px",
														src: "https://framerusercontent.com/images/qNZQLErHYt1BnULpExSwp4A56QU.svg?width=28&height=28",
													}}
													className={"framer-19agui4"}
													layoutDependency={layoutDependency}
													layoutId={"zPlDcXobL"}
													{...addPropertyOverrides(
														{
															hskaPnjRh: {
																background: {
																	alt: "",
																	fit: "fit",
																	intrinsicHeight: 28,
																	intrinsicWidth: 28,
																	pixelHeight: 28,
																	pixelWidth: 28,
																	positionX: "center",
																	positionY: "center",
																	sizes: "22px",
																	src: "https://framerusercontent.com/images/qNZQLErHYt1BnULpExSwp4A56QU.svg?width=28&height=28",
																},
															},
															QGilQypG9: {
																background: {
																	alt: "",
																	fit: "fit",
																	intrinsicHeight: 28,
																	intrinsicWidth: 28,
																	pixelHeight: 28,
																	pixelWidth: 28,
																	positionX: "center",
																	positionY: "center",
																	sizes: "18px",
																	src: "https://framerusercontent.com/images/qNZQLErHYt1BnULpExSwp4A56QU.svg?width=28&height=28",
																},
															},
														},
														baseVariant,
														gestureVariant,
													)}
												/>
											</motion.div>
										</motion.div>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-a8lmxa"}
											data-framer-name={"Right"}
											layoutDependency={layoutDependency}
											layoutId={"BMSw2qPBt"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-2fgx92"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Sv3QOika3"}
												style={{
													"--extracted-a0htzi":
														"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														suppressHydrationWarning={true}
														className={"framer-styles-preset-8gnvci"}
														data-styles-preset={"Me3diAYP1"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "start",
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229)))",
														}}
													>
														{"Book your free intro session"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-cyskj3"}
												data-framer-name={"Info"}
												layoutDependency={layoutDependency}
												layoutId={"cWKBQFwLC"}
											>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-klv4p5"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"PLk7sgvK4"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-7580yq"}
															data-styles-preset={"ESdyUGyJl"}
															dir={"auto"}
															style={{
																"--framer-text-alignment": "start",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229)))",
															}}
														>
															{"15-30 min"}
														</motion.p>
													</React.Fragment>
												</RichText>
												<motion.div
													suppressHydrationWarning={true}
													className={"framer-1im7ekn"}
													layoutDependency={layoutDependency}
													layoutId={"g3J3z3q1P"}
													style={{
														backgroundColor:
															"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
														borderBottomLeftRadius: 10,
														borderBottomRightRadius: 10,
														borderTopLeftRadius: 10,
														borderTopRightRadius: 10,
													}}
												/>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-10jvy19"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"SrjP4WtFa"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-7580yq"}
															data-styles-preset={"ESdyUGyJl"}
															dir={"auto"}
															style={{
																"--framer-text-alignment": "start",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229)))",
															}}
														>
															{"One-on-one"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</motion.div>
									</motion.div>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-13gh8vr"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"yU4zQHQPv"}
										style={{
											backgroundColor:
												"var(--token-1e504858-12f8-4dd0-88c3-45ca2b94ee6a, rgba(255, 255, 255, 0.1))",
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-azd0w6"}
										data-framer-name={"Right"}
										layoutDependency={layoutDependency}
										layoutId={"ErEYSlxSi"}
									>
										<ResolveLinks
											suppressHydrationWarning={true}
											links={[
												{
													href: {
														webPageId: "peTwLqil9",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "peTwLqil9",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "peTwLqil9",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={54}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-t2yn5v-container"}
														layoutDependency={layoutDependency}
														layoutId={"gq0R4NYxX-container"}
														nodeId={"gq0R4NYxX"}
														rendersWithMotion={true}
														scopeId={"S3G1yu2Yh"}
													>
														{_jsx(stdin_default, {
															suppressHydrationWarning: true,
															height: "100%",
															id: "gq0R4NYxX",
															Kiib3s3Y3: "Book the intro session",
															layoutId: "gq0R4NYxX",
															toG7h_P8o: resolvedLinks[0],
															variant: matchVariant("EUoTryFDz"),
															width: "100%",
															Y5KJgXrXk: false,
															...addPropertyOverrides(
																{
																	hskaPnjRh: {
																		toG7h_P8o: resolvedLinks[1],
																		variant: matchVariant("ltttFCNrV"),
																	},
																	QGilQypG9: {
																		toG7h_P8o: resolvedLinks[2],
																		variant: matchVariant("ltttFCNrV"),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion.div>
								</MotionDivWithFX>
							</motion.div>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-17y7lkb"}
							data-framer-name={"BG Decor"}
							layoutDependency={layoutDependency}
							layoutId={"u1whOPQhL"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1p2kkwi"}
								data-framer-name={"Left"}
								layoutDependency={layoutDependency}
								layoutId={"zNa0zCB5R"}
							>
								<Image1
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 763,
										intrinsicWidth: 684,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												150 +
												(0 +
													((componentViewport?.height || 702) -
														150 -
														0 -
														((componentViewport?.height || 702) - 150 - 0) *
															1) /
														2) +
												((componentViewport?.height || 702) - 150 - 0) * 1 -
												580,
										),
										pixelHeight: 763,
										pixelWidth: 684,
										sizes: "519.9476px",
										src: "https://framerusercontent.com/images/KITCFqoLDqQXdqMCCYX4dCTzRNo.png?width=684&height=763",
										srcSet:
											"https://framerusercontent.com/images/KITCFqoLDqQXdqMCCYX4dCTzRNo.png?width=684&height=763 684w",
									}}
									className={"framer-17l1ywc"}
									fitImageDimension={"width"}
									layoutDependency={layoutDependency}
									layoutId={"VgXwzIyMw"}
									{...addPropertyOverrides(
										{
											hskaPnjRh: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 763,
													intrinsicWidth: 684,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															150 +
															(0 +
																((componentViewport?.height || 680) -
																	150 -
																	0 -
																	((componentViewport?.height || 680) -
																		150 -
																		0) *
																		1) /
																	2) +
															((componentViewport?.height || 680) - 150 - 0) *
																1 -
															400,
													),
													pixelHeight: 763,
													pixelWidth: 684,
													sizes: "358.5845px",
													src: "https://framerusercontent.com/images/KITCFqoLDqQXdqMCCYX4dCTzRNo.png?width=684&height=763",
													srcSet:
														"https://framerusercontent.com/images/KITCFqoLDqQXdqMCCYX4dCTzRNo.png?width=684&height=763 684w",
												},
											},
											QGilQypG9: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 763,
													intrinsicWidth: 684,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															150 +
															(0 +
																((componentViewport?.height || 200) -
																	150 -
																	0 -
																	((componentViewport?.height || 200) -
																		150 -
																		0) *
																		1) /
																	2) +
															((componentViewport?.height || 200) - 150 - 0) *
																1 -
															200,
													),
													pixelHeight: 763,
													pixelWidth: 684,
													sizes: "179.2923px",
													src: "https://framerusercontent.com/images/KITCFqoLDqQXdqMCCYX4dCTzRNo.png?width=684&height=763",
													srcSet:
														"https://framerusercontent.com/images/KITCFqoLDqQXdqMCCYX4dCTzRNo.png?width=684&height=763 684w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-o0lc0"}
								data-framer-name={"Right"}
								layoutDependency={layoutDependency}
								layoutId={"ICrdmoX1d"}
							>
								<Image1
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fit",
										intrinsicHeight: 640,
										intrinsicWidth: 571,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												150 +
												(0 +
													((componentViewport?.height || 702) -
														150 -
														0 -
														((componentViewport?.height || 702) - 150 - 0) *
															1) /
														2) +
												((componentViewport?.height || 702) - 150 - 0) * 1 -
												494,
										),
										pixelHeight: 640,
										pixelWidth: 571,
										positionX: "center",
										positionY: "center",
										sizes: "458.5844px",
										src: "https://framerusercontent.com/images/3fIhq7ij32qpJo01OGJstWOA3M.png?width=571&height=640",
										srcSet:
											"https://framerusercontent.com/images/3fIhq7ij32qpJo01OGJstWOA3M.png?width=571&height=640 571w",
									}}
									className={"framer-1ay7ry0"}
									fitImageDimension={"width"}
									layoutDependency={layoutDependency}
									layoutId={"bRFlXiHlJ"}
									{...addPropertyOverrides(
										{
											hskaPnjRh: {
												background: {
													alt: "",
													fit: "fit",
													intrinsicHeight: 640,
													intrinsicWidth: 571,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															150 +
															(0 +
																((componentViewport?.height || 680) -
																	150 -
																	0 -
																	((componentViewport?.height || 680) -
																		150 -
																		0) *
																		1) /
																	2) +
															((componentViewport?.height || 680) - 150 - 0) *
																1 -
															350,
													),
													pixelHeight: 640,
													pixelWidth: 571,
													positionX: "center",
													positionY: "center",
													sizes: "330.1094px",
													src: "https://framerusercontent.com/images/3fIhq7ij32qpJo01OGJstWOA3M.png?width=571&height=640",
													srcSet:
														"https://framerusercontent.com/images/3fIhq7ij32qpJo01OGJstWOA3M.png?width=571&height=640 571w",
												},
											},
											QGilQypG9: {
												background: {
													alt: "",
													fit: "fit",
													intrinsicHeight: 640,
													intrinsicWidth: 571,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															150 +
															(0 +
																((componentViewport?.height || 200) -
																	150 -
																	0 -
																	((componentViewport?.height || 200) -
																		150 -
																		0) *
																		1) /
																	2) +
															((componentViewport?.height || 200) - 150 - 0) *
																1 -
															180,
													),
													pixelHeight: 640,
													pixelWidth: 571,
													positionX: "center",
													positionY: "center",
													sizes: "178.4375px",
													src: "https://framerusercontent.com/images/3fIhq7ij32qpJo01OGJstWOA3M.png?width=571&height=640",
													srcSet:
														"https://framerusercontent.com/images/3fIhq7ij32qpJo01OGJstWOA3M.png?width=571&height=640 571w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	".framer-fLY7v.framer-vo8f5i, .framer-fLY7v .framer-vo8f5i { display: block; }",
	".framer-fLY7v.framer-1gxhp5z { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 150px 0px 150px 0px; position: relative; width: 1200px; }",
	".framer-fLY7v .framer-18nf041 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; z-index: 2; }",
	".framer-fLY7v .framer-xy79ny { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-fLY7v .framer-19o8lku { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; max-width: 900px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-fLY7v .framer-1qg7ern { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-fLY7v .framer-u8h2tx-container, .framer-fLY7v .framer-t2yn5v-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-fLY7v .framer-1xtf8ag { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-fLY7v .framer-5y94iv, .framer-fLY7v .framer-12k8zzo, .framer-fLY7v .framer-xzurxb, .framer-fLY7v .framer-8uvcru, .framer-fLY7v .framer-28n2wi { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-fLY7v .framer-1b2evln { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 26px 0px; position: relative; width: min-content; }",
	".framer-fLY7v .framer-1f6v95z { -webkit-user-select: none; aspect-ratio: 1.032258064516129 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 32px; will-change: var(--framer-will-change-filter-override, filter); z-index: 1; }",
	".framer-fLY7v .framer-8jpqwa { -webkit-user-select: none; bottom: 0px; flex: none; height: 44px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; will-change: var(--framer-will-change-filter-override, filter); z-index: 1; }",
	".framer-fLY7v .framer-vhve7i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; max-width: 600px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-fLY7v .framer-eic37t, .framer-fLY7v .framer-2fgx92 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-fLY7v .framer-6u7ipj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 810px; overflow: hidden; padding: 20px 30px 20px 30px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-fLY7v .framer-i9vv7s { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-fLY7v .framer-1hrmsmn, .framer-fLY7v .framer-azd0w6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-fLY7v .framer-l61qnx { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: auto; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 60px; will-change: var(--framer-will-change-override, transform); }",
	".framer-fLY7v .framer-19agui4 { aspect-ratio: 1 / 1; flex: none; height: auto; overflow: hidden; position: relative; width: 28px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-fLY7v .framer-a8lmxa { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-fLY7v .framer-cyskj3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-fLY7v .framer-klv4p5, .framer-fLY7v .framer-10jvy19 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: auto; }",
	".framer-fLY7v .framer-1im7ekn { flex: none; height: 4px; overflow: hidden; position: relative; width: 4px; will-change: var(--framer-will-change-override, transform); }",
	".framer-fLY7v .framer-13gh8vr { align-self: stretch; flex: none; height: auto; overflow: hidden; position: relative; width: 2px; }",
	".framer-fLY7v .framer-17y7lkb { -webkit-user-select: none; align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; justify-content: flex-start; left: 0px; overflow: visible; padding: 0px; pointer-events: none; position: absolute; right: 0px; top: 150px; user-select: none; z-index: 1; }",
	".framer-fLY7v .framer-1p2kkwi { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-fLY7v .framer-17l1ywc { -webkit-user-select: none; bottom: 0px; flex: none; height: 580px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; user-select: none; width: auto; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-fLY7v .framer-o0lc0 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 3; }",
	".framer-fLY7v .framer-1ay7ry0 { -webkit-user-select: none; bottom: -20px; flex: none; height: 514px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; width: auto; will-change: var(--framer-will-change-filter-override, filter); z-index: 2; }",
	".framer-fLY7v.framer-v-1igazh3.framer-1gxhp5z { padding: 100px 0px 100px 0px; width: 810px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-xy79ny { gap: 40px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-1xtf8ag { gap: 0px 10px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-1b2evln { padding: 0px 20px 6px 0px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-6u7ipj { gap: 20px; padding: 20px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-l61qnx { width: 50px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-19agui4 { width: 22px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-17l1ywc { height: 400px; }",
	".framer-fLY7v.framer-v-1igazh3 .framer-1ay7ry0 { height: 370px; right: -30px; }",
	".framer-fLY7v.framer-v-bvrs6s.framer-1gxhp5z { padding: 80px 0px 150px 0px; width: 360px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-18nf041 { padding: 0px 20px 0px 20px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-xy79ny { gap: 30px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-1xtf8ag { gap: 0px 8px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-6u7ipj { flex-direction: column; gap: 20px; padding: 20px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-i9vv7s { flex: none; gap: 10px; width: 100%; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-l61qnx { width: 40px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-19agui4 { width: 18px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-13gh8vr { align-self: unset; height: 1px; width: 100%; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-17l1ywc { height: 200px; }",
	".framer-fLY7v.framer-v-bvrs6s .framer-1ay7ry0 { height: 200px; right: -30px; }",
	...css2,
	...css,
	...css3,
];
var FramerS3G1yu2Yh = withCSS(Component, css4, "framer-fLY7v");
var stdin_default3 = FramerS3G1yu2Yh;
FramerS3G1yu2Yh.displayName = "CTA Mentor";
FramerS3G1yu2Yh.defaultProps = {
	height: 702,
	width: 1200,
};
addPropertyControls(FramerS3G1yu2Yh, {
	variant: {
		options: ["i4bpSSNVm", "hskaPnjRh", "QGilQypG9"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	T2OJLVTsb: {
		defaultValue: "",
		title: "Title",
		type: ControlType.String,
	},
	onT2OJLVTsbChange: {
		changes: "T2OJLVTsb",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerS3G1yu2Yh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PreTitleFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerS3G1yu2Yh.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:cta-mentor
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaMentorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var cta_mentor_default = ComponentWithRoot;
export { cta_mentor_default as default };
