// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6ONBAXWQ.js";
import { stdin_default } from "./chunks/chunk-FUMATQXC.js";
import { className, css, fonts } from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:mentor-section-1-hero
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/LbQ9QJ42IB7IhkyuwcFl/nQdN7Fw1I1syFnDgWYS0/FWhFveOp4.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PreTitleFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var cycleOrder = ["Gcdpr78ra", "z8p6KVgPN", "RSazXk8zr"];
var serializationHash = "framer-k1khP";
var variantClassNames = {
	Gcdpr78ra: "framer-v-z30r3l",
	RSazXk8zr: "framer-v-10rrwdt",
	z8p6KVgPN: "framer-v-jo492o",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var bw5wYLxeb_YfmS2tChUfdu0v1MtY = void 0;
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition3 = {
	delay: 0.35,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "Gcdpr78ra",
	Phone: "RSazXk8zr",
	Tablet: "z8p6KVgPN",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Gcdpr78ra",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Gcdpr78ra",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-z30r3l",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Gcdpr78ra"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								RSazXk8zr: {
									"data-framer-name": "Phone",
								},
								z8p6KVgPN: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-7rxg2t"}
							data-framer-name={"Hero"}
							layoutDependency={layoutDependency}
							layoutId={"iEcUEkSAK"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-n9x8i4"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"Y9D3PzpRx"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1x3d2x5"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"tc251ffw5"}
								>
									<MotionDivWithFXWithOptimizedAppearEffect
										suppressHydrationWarning={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-xfbb6q"}
										data-framer-appear-id={"xfbb6q"}
										data-framer-name={"Heading"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"FVPksTdHF"}
										optimized={true}
									>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={34}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-n8dlja-container"}
												layoutDependency={layoutDependency}
												layoutId={"m9Cg_maxp-container"}
												nodeId={"m9Cg_maxp"}
												rendersWithMotion={true}
												scopeId={"FWhFveOp4"}
											>
												{_jsx(stdin_default, {
													suppressHydrationWarning: true,
													height: "100%",
													HJ8LmVVDm:
														"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
													id: "m9Cg_maxp",
													layoutId: "m9Cg_maxp",
													qzeUwXZ6t:
														"var(--token-9be2179a-d4c3-4b1c-a57e-66ad0ebb844d, rgb(232, 114, 44))",
													wCKXxEnrH: "Vetted twice \xB7 Certified educators",
													width: "100%",
													ZFJwwHvsK:
														"var(--token-d0e4cb96-2373-4292-a52b-0c70e08d9898, rgb(246, 215, 232))",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-bdxvhu"}
											data-framer-name={"Heading"}
											layoutDependency={layoutDependency}
											layoutId={"OLkLzt7Cb"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-7or3wq"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"LKCBfQi97"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1w1zhlt"}
														data-styles-preset={"c4bkaT15f"}
														dir={"auto"}
													>
														{"Meet"}
													</motion.h1>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-ccr3t5"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"zgZYvgFiV"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1w1zhlt"}
														data-styles-preset={"c4bkaT15f"}
														dir={"auto"}
													>
														{"the"}
													</motion.h1>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-doh9se"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"eBk3ZqApJ"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1w1zhlt"}
														data-styles-preset={"c4bkaT15f"}
														dir={"auto"}
													>
														{"minds"}
													</motion.h1>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1pgzyen"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Cs4HTl6U3"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1w1zhlt"}
														data-styles-preset={"c4bkaT15f"}
														dir={"auto"}
													>
														{"the"}
													</motion.h1>
												</React.Fragment>
											</RichText>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1yiqv2b"}
												data-framer-name={"Highlight"}
												layoutDependency={layoutDependency}
												layoutId={"aeQJmhQ83"}
											>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-bbbbbo"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"FDtCwWvEh"}
													style={{
														"--extracted-gdpscs":
															"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
														rotate: 5,
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.h1
															suppressHydrationWarning={true}
															className={"framer-styles-preset-1w1zhlt"}
															data-styles-preset={"c4bkaT15f"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-gdpscs, var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100)))",
															}}
														>
															{"learning"}
														</motion.h1>
													</React.Fragment>
												</RichText>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 34,
														intrinsicWidth: 33,
														pixelHeight: 34,
														pixelWidth: 33,
														sizes: "32px",
														src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
													}}
													className={"framer-wlov9d"}
													data-framer-name={"Top Decor"}
													layoutDependency={layoutDependency}
													layoutId={"tb_hbROMb"}
													{...addPropertyOverrides(
														{
															RSazXk8zr: {
																background: {
																	alt: "",
																	fit: "fill",
																	intrinsicHeight: 34,
																	intrinsicWidth: 33,
																	pixelHeight: 34,
																	pixelWidth: 33,
																	sizes: "26px",
																	src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
																},
															},
														},
														baseVariant,
														gestureVariant,
													)}
												/>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "stretch",
														intrinsicHeight: 46,
														intrinsicWidth: 219,
														pixelHeight: 46,
														pixelWidth: 219,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/JrJVDghR4XSfM4fEkVG4YlBTu0E.svg?width=219&height=46",
													}}
													className={"framer-tjsjin"}
													data-framer-name={"Bottom Decor"}
													layoutDependency={layoutDependency}
													layoutId={"rIUMpNwno"}
												/>
											</motion.div>
										</motion.div>
									</MotionDivWithFXWithOptimizedAppearEffect>
									<RichTextWithFXWithOptimizedAppearEffect
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation2}
										className={"framer-1pd9qrz"}
										data-framer-appear-id={"1pd9qrz"}
										fonts={["Inter"]}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"B7RUmk0_S"}
										optimized={true}
										text={bw5wYLxeb_YfmS2tChUfdu0v1MtY}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-7580yq"}
												data-styles-preset={"ESdyUGyJl"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{
													"We rebuild confidence first, then speed. From number sense to calculus, every learner gets a plan built around their actual gaps not a generic worksheet pile."
												}
											</motion.p>
										</React.Fragment>
									</RichTextWithFXWithOptimizedAppearEffect>
								</motion.div>
							</motion.div>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	".framer-k1khP.framer-1fv175x, .framer-k1khP .framer-1fv175x { display: block; }",
	".framer-k1khP.framer-z30r3l { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-k1khP .framer-7rxg2t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 146px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-k1khP .framer-n9x8i4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-k1khP .framer-1x3d2x5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 760px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-k1khP .framer-xfbb6q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-k1khP .framer-n8dlja-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-k1khP .framer-bdxvhu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 12px; height: min-content; justify-content: center; max-width: 860px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-k1khP .framer-7or3wq, .framer-k1khP .framer-ccr3t5, .framer-k1khP .framer-doh9se, .framer-k1khP .framer-1pgzyen, .framer-k1khP .framer-bbbbbo { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-k1khP .framer-1yiqv2b { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 26px 0px; position: relative; width: min-content; }",
	".framer-k1khP .framer-wlov9d { -webkit-user-select: none; aspect-ratio: 1 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 32px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-k1khP .framer-tjsjin { -webkit-user-select: none; bottom: 0px; flex: none; height: 44px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-k1khP .framer-1pd9qrz { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-k1khP.framer-v-jo492o.framer-z30r3l { width: 810px; }",
	".framer-k1khP.framer-v-jo492o .framer-7rxg2t { padding: 130px 0px 0px 0px; }",
	".framer-k1khP.framer-v-jo492o .framer-bdxvhu { gap: 8px 10px; }",
	".framer-k1khP.framer-v-10rrwdt.framer-z30r3l { width: 390px; }",
	".framer-k1khP.framer-v-10rrwdt .framer-7rxg2t { padding: 100px 0px 0px 0px; }",
	".framer-k1khP.framer-v-10rrwdt .framer-n9x8i4 { padding: 0px 20px 0px 20px; }",
	".framer-k1khP.framer-v-10rrwdt .framer-bdxvhu { gap: 0px 10px; }",
	".framer-k1khP.framer-v-10rrwdt .framer-wlov9d { width: 26px; }",
	...css2,
	...css,
];
var FramerFWhFveOp4 = withCSS(Component, css3, "framer-k1khP");
var stdin_default2 = FramerFWhFveOp4;
FramerFWhFveOp4.displayName = "Mentor Section 1 \u2014 Hero";
FramerFWhFveOp4.defaultProps = {
	height: 200,
	width: 200,
};
addPropertyControls(FramerFWhFveOp4, {
	variant: {
		options: ["Gcdpr78ra", "z8p6KVgPN", "RSazXk8zr"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerFWhFveOp4,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PreTitleFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerFWhFveOp4.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:mentor-section-1-hero
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MentorSection1HeroFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var mentor_section_1_hero_default = ComponentWithRoot;
export { mentor_section_1_hero_default as default };


// --- unframer-cms-binding (generated by scripts/bind-cms.mjs) ---
export function __bindCmsFields(values) {
	if ("bw5wYLxeb_YfmS2tChU" in values) bw5wYLxeb_YfmS2tChUfdu0v1MtY = values["bw5wYLxeb_YfmS2tChU"];
}
export const __cmsFieldIds = ["bw5wYLxeb_YfmS2tChU"];
