// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-MLB3MC5T.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-AOWK4JFD.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-4XRGEVGL.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-6ONBAXWQ.js";
import {
	className as className8,
	css as css8,
	fonts as fonts8,
} from "./chunks/chunk-EPDNPLDL.js";
import { className, css, fonts } from "./chunks/chunk-RFLCCK3R.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-R5PSICTC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:mentor-detail-section-2-session
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wFpaeQrsJ7swHnrDJ67c/BAWdXdnhfh7iFtKn3WKZ/SfnukpMcS.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var RichTextWithFX = withFX(RichText);
var cycleOrder = ["sMazIY2DF", "Ni_WTb8wP", "yidxqcXpN"];
var serializationHash = "framer-JXYfh";
var variantClassNames = {
	Ni_WTb8wP: "framer-v-1d0jd9",
	sMazIY2DF: "framer-v-zyid19",
	yidxqcXpN: "framer-v-15zsp1p",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var QLObxbGfmK3J5jRO36 = void 0;
var XNLdspowHK3J5jRO36 = void 0;
var EJZU77C18K3J5jRO36 = void 0;
var EkhrKhG8kK3J5jRO36 = void 0;
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var transition3 = {
	delay: 0.3,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var transition4 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 30,
};
var transition5 = {
	delay: 0.5,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 30,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "sMazIY2DF",
	Phone: "yidxqcXpN",
	Tablet: "Ni_WTb8wP",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "sMazIY2DF",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className9,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "sMazIY2DF",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className8,
		className5,
		className6,
		className4,
		className3,
		className7,
		className2,
		className,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(QLObxbGfmK3J5jRO36);
	const visible1 = isSet(XNLdspowHK3J5jRO36);
	const visible2 = isSet(EJZU77C18K3J5jRO36);
	const visible3 = isSet(EkhrKhG8kK3J5jRO36);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-zyid19",
							className9,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"sMazIY2DF"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								Ni_WTb8wP: {
									"data-framer-name": "Tablet",
								},
								yidxqcXpN: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-1q6h30z"}
							data-framer-name={"Session"}
							layoutDependency={layoutDependency}
							layoutId={"NYNDAMdf3"}
							style={{
								backgroundColor:
									"var(--token-e8cec243-b334-4568-a85b-a75cea534593, rgb(214, 229, 154))",
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1rs90c5"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"W1sqgpSK5"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-14449ps"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"KfMEeEotj"}
								>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-bklhhi"}
										data-framer-name={"Heading"}
										layoutDependency={layoutDependency}
										layoutId={"nnxA0MaJv"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1i11tz7"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"z5QWrYJRd"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h2
													suppressHydrationWarning={true}
													className={"framer-styles-preset-jcbbly"}
													data-styles-preset={"UXoQEMm1m"}
													dir={"auto"}
												>
													{"How"}
												</motion.h2>
											</React.Fragment>
										</RichText>
										{visible !== false && (
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1815fcn"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"fYysB9uw1"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={QLObxbGfmK3J5jRO36}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-jcbbly"}
														data-styles-preset={"UXoQEMm1m"}
														dir={"auto"}
													>
														{"Maya"}
													</motion.h2>
												</React.Fragment>
											</RichText>
										)}
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1n4zct1"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"g2IFz2d_B"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h2
													suppressHydrationWarning={true}
													className={"framer-styles-preset-jcbbly"}
													data-styles-preset={"UXoQEMm1m"}
													dir={"auto"}
												>
													{"runs"}
												</motion.h2>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1oh8anu"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"NvwipE3yj"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h2
													suppressHydrationWarning={true}
													className={"framer-styles-preset-jcbbly"}
													data-styles-preset={"UXoQEMm1m"}
													dir={"auto"}
												>
													{"a"}
												</motion.h2>
											</React.Fragment>
										</RichText>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-17ecu9s"}
											data-framer-name={"Highlight"}
											layoutDependency={layoutDependency}
											layoutId={"HdH3v4Src"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-11vtzjs"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"F90avJEiL"}
												style={{
													"--extracted-1of0zx5":
														"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
													rotate: 5,
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-jcbbly"}
														data-styles-preset={"UXoQEMm1m"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100)))",
														}}
													>
														{"session"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<Image1
												suppressHydrationWarning={true}
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 34,
													intrinsicWidth: 33,
													pixelHeight: 34,
													pixelWidth: 33,
													sizes: "32px",
													src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
												}}
												className={"framer-qvsyuw"}
												data-framer-name={"Top Decor"}
												layoutDependency={layoutDependency}
												layoutId={"gtDEE38Co"}
											/>
											<Image1
												suppressHydrationWarning={true}
												background={{
													alt: "",
													fit: "stretch",
													intrinsicHeight: 46,
													intrinsicWidth: 219,
													pixelHeight: 46,
													pixelWidth: 219,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/JrJVDghR4XSfM4fEkVG4YlBTu0E.svg?width=219&height=46",
												}}
												className={"framer-1nu033a"}
												data-framer-name={"Bottom Decor"}
												layoutDependency={layoutDependency}
												layoutId={"NJX7yiEIt"}
											/>
										</motion.div>
									</MotionDivWithFX>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-85acs8"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"TShf26pwJ"}
									>
										{visible1 !== false && (
											<RichTextWithFX
												suppressHydrationWarning={true}
												__framer__animate={{
													transition: transition3,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__exit={animation2}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-qem9xx"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"e9ahymP81"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
													"--framer-paragraph-spacing": "10px",
												}}
												stylesPresetsClassNames={{
													a: "framer-styles-preset-eke6e",
													h1: "framer-styles-preset-1w1zhlt",
													h2: "framer-styles-preset-jcbbly",
													h3: "framer-styles-preset-1mec8v8",
													h4: "framer-styles-preset-8gnvci",
													h5: "framer-styles-preset-1limcq0",
													h6: "framer-styles-preset-1fxd4ok",
													p: "framer-styles-preset-7580yq",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												{XNLdspowHK3J5jRO36}
											</RichTextWithFX>
										)}
										{visible2 !== false && (
											<RichTextWithFX
												suppressHydrationWarning={true}
												__framer__animate={{
													transition: transition4,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__exit={animation3}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1unucp0"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"emji1yeLs"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												stylesPresetsClassNames={{
													a: "framer-styles-preset-eke6e",
													h1: "framer-styles-preset-1w1zhlt",
													h2: "framer-styles-preset-jcbbly",
													h3: "framer-styles-preset-1mec8v8",
													h4: "framer-styles-preset-8gnvci",
													h5: "framer-styles-preset-1limcq0",
													h6: "framer-styles-preset-1fxd4ok",
													p: "framer-styles-preset-7580yq",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												{EJZU77C18K3J5jRO36}
											</RichTextWithFX>
										)}
										{visible3 !== false && (
											<RichTextWithFX
												suppressHydrationWarning={true}
												__framer__animate={{
													transition: transition5,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__exit={animation4}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1ub4j51"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"wGNfAud6L"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												stylesPresetsClassNames={{
													a: "framer-styles-preset-eke6e",
													h1: "framer-styles-preset-1w1zhlt",
													h2: "framer-styles-preset-jcbbly",
													h3: "framer-styles-preset-1mec8v8",
													h4: "framer-styles-preset-8gnvci",
													h5: "framer-styles-preset-1limcq0",
													h6: "framer-styles-preset-1fxd4ok",
													p: "framer-styles-preset-7580yq",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												{EkhrKhG8kK3J5jRO36}
											</RichTextWithFX>
										)}
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css9 = [
	".framer-JXYfh.framer-i393g8, .framer-JXYfh .framer-i393g8 { display: block; }",
	".framer-JXYfh.framer-zyid19 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-JXYfh .framer-1q6h30z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 150px 0px 150px 0px; position: relative; width: 100%; }",
	".framer-JXYfh .framer-1rs90c5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-JXYfh .framer-14449ps { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JXYfh .framer-bklhhi { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 12px; height: min-content; justify-content: center; max-width: 760px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JXYfh .framer-1i11tz7, .framer-JXYfh .framer-1815fcn, .framer-JXYfh .framer-1n4zct1, .framer-JXYfh .framer-1oh8anu, .framer-JXYfh .framer-11vtzjs { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-JXYfh .framer-17ecu9s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 26px 0px; position: relative; width: min-content; }",
	".framer-JXYfh .framer-qvsyuw { -webkit-user-select: none; aspect-ratio: 1.032258064516129 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 32px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-JXYfh .framer-1nu033a { -webkit-user-select: none; bottom: 0px; flex: none; height: 44px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-JXYfh .framer-85acs8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JXYfh .framer-qem9xx, .framer-JXYfh .framer-1unucp0, .framer-JXYfh .framer-1ub4j51 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-JXYfh.framer-v-1d0jd9.framer-zyid19 { width: 810px; }",
	".framer-JXYfh.framer-v-1d0jd9 .framer-1q6h30z { padding: 100px 0px 100px 0px; }",
	".framer-JXYfh.framer-v-1d0jd9 .framer-14449ps { gap: 40px; }",
	".framer-JXYfh.framer-v-1d0jd9 .framer-bklhhi { gap: 0px 10px; }",
	".framer-JXYfh.framer-v-1d0jd9 .framer-85acs8 { align-content: unset; align-items: unset; display: grid; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); }",
	".framer-JXYfh.framer-v-1d0jd9 .framer-qem9xx, .framer-JXYfh.framer-v-1d0jd9 .framer-1unucp0, .framer-JXYfh.framer-v-15zsp1p .framer-qem9xx, .framer-JXYfh.framer-v-15zsp1p .framer-1unucp0 { align-self: start; flex: none; height: 100%; justify-self: start; width: 100%; }",
	".framer-JXYfh.framer-v-1d0jd9 .framer-1ub4j51 { align-self: start; flex: none; grid-column: span 2; height: 100%; justify-self: start; width: 100%; }",
	".framer-JXYfh.framer-v-15zsp1p.framer-zyid19 { width: 390px; }",
	".framer-JXYfh.framer-v-15zsp1p .framer-1q6h30z { padding: 80px 0px 80px 0px; }",
	".framer-JXYfh.framer-v-15zsp1p .framer-1rs90c5 { padding: 0px 20px 0px 20px; }",
	".framer-JXYfh.framer-v-15zsp1p .framer-14449ps { gap: 30px; }",
	".framer-JXYfh.framer-v-15zsp1p .framer-bklhhi { gap: 0px 8px; }",
	".framer-JXYfh.framer-v-15zsp1p .framer-85acs8 { align-content: unset; align-items: unset; display: grid; gap: 20px; grid-auto-rows: min-content; grid-template-columns: repeat(1, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); }",
	".framer-JXYfh.framer-v-15zsp1p .framer-1ub4j51 { align-self: start; flex: none; grid-column: span 1; height: 100%; justify-self: start; width: 100%; }",
	...css8,
	...css5,
	...css6,
	...css4,
	...css3,
	...css7,
	...css2,
	...css,
];
var FramerSfnukpMcS = withCSS(Component, css9, "framer-JXYfh");
var stdin_default = FramerSfnukpMcS;
FramerSfnukpMcS.displayName = "Mentor Detail Section 2 \u2014 Session";
FramerSfnukpMcS.defaultProps = {
	height: 200,
	width: 200,
};
addPropertyControls(FramerSfnukpMcS, {
	variant: {
		options: ["sMazIY2DF", "Ni_WTb8wP", "yidxqcXpN"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerSfnukpMcS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mentor-detail-section-2-session
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MentorDetailSection2SessionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var mentor_detail_section_2_session_default = ComponentWithRoot;
export { mentor_detail_section_2_session_default as default };


// --- unframer-cms-binding (generated by scripts/bind-cms.mjs) ---
export function __bindCmsFields(values) {
	if ("QLObxbGfm" in values) QLObxbGfmK3J5jRO36 = values["QLObxbGfm"];
	if ("XNLdspowH" in values) XNLdspowHK3J5jRO36 = values["XNLdspowH"];
	if ("EJZU77C18" in values) EJZU77C18K3J5jRO36 = values["EJZU77C18"];
	if ("EkhrKhG8k" in values) EkhrKhG8kK3J5jRO36 = values["EkhrKhG8k"];
}
export const __cmsFieldIds = ["QLObxbGfm","XNLdspowH","EJZU77C18","EkhrKhG8k"];
