// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet - Close' | 'Tablet - Open' | 'Phone - Close' | 'Phone - Open' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-RFLCCK3R.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-BQQOF2QQ.js";
import { stdin_default } from "./chunks/chunk-DPP5EL47.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-C742CGXR.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:navigation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/72kK7BNtuZACfpMH5VVV/6q7mTlM5thplHRbcwz2f/jkTp0PN3r.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BrandLogoFonts = getFonts(stdin_default2);
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = [
	"XNilpKObr",
	"QuqZu40Aj",
	"Ojr4RjW9Y",
	"gAxzkC4Cq",
	"fCyPYonB5",
];
var serializationHash = "framer-ahWi0";
var variantClassNames = {
	fCyPYonB5: "framer-v-jhl8yh",
	gAxzkC4Cq: "framer-v-gs5urc",
	Ojr4RjW9Y: "framer-v-8ikj6b",
	QuqZu40Aj: "framer-v-40idda",
	XNilpKObr: "framer-v-1q36u8u",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Phone - Close": "gAxzkC4Cq",
	"Phone - Open": "fCyPYonB5",
	"Tablet - Close": "QuqZu40Aj",
	"Tablet - Open": "Ojr4RjW9Y",
	Desktop: "XNilpKObr",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XNilpKObr",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XNilpKObr",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const uDK4ahqmlf6m6lj = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("QuqZu40Aj"), 100);
	});
	const uDK4ahqml1hoz6s = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("gAxzkC4Cq"), 100);
	});
	const onTapf6m6lj = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("QuqZu40Aj"), 100);
	});
	const onTap1hoz6s = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("gAxzkC4Cq"), 100);
	});
	const onTap1h55cr = activeVariantCallback(async (...args) => {
		setVariant("Ojr4RjW9Y");
	});
	const onTap19kykfp = activeVariantCallback(async (...args) => {
		setVariant("fCyPYonB5");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["QuqZu40Aj", "gAxzkC4Cq"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (["gAxzkC4Cq", "fCyPYonB5"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed2 = () => {
		if (
			["QuqZu40Aj", "Ojr4RjW9Y", "gAxzkC4Cq", "fCyPYonB5"].includes(baseVariant)
		)
			return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.nav
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1q36u8u",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"XNilpKObr"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						variants={{
							fCyPYonB5: {
								backgroundColor:
									"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
							},
							gAxzkC4Cq: {
								backgroundColor:
									"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
							},
							Ojr4RjW9Y: {
								backgroundColor:
									"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
							},
							QuqZu40Aj: {
								backgroundColor:
									"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
							},
						}}
						{...addPropertyOverrides(
							{
								fCyPYonB5: {
									"data-framer-name": "Phone - Open",
								},
								gAxzkC4Cq: {
									"data-framer-name": "Phone - Close",
								},
								Ojr4RjW9Y: {
									"data-framer-name": "Tablet - Open",
								},
								QuqZu40Aj: {
									"data-framer-name": "Tablet - Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1r5rn89"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"DQepz8WsI"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1s4y7z3"}
								data-framer-name={"Grid Nav"}
								layoutDependency={layoutDependency}
								layoutId={"SFbn7XGLK"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-82g7t8"}
									data-framer-name={"Left"}
									layoutDependency={layoutDependency}
									layoutId={"TWQG1ONyA"}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={32}
										y={
											(componentViewport?.y || 0) +
											(20 + ((componentViewport?.height || 86) - 40 - 54) / 2) +
											0 +
											11 +
											0
										}
										{...addPropertyOverrides(
											{
												fCyPYonB5: {
													y:
														(componentViewport?.y || 0) +
														(10 +
															((componentViewport?.height || 200) - 24 - 34) /
																2) +
														0 +
														1 +
														0,
												},
												gAxzkC4Cq: {
													y:
														(componentViewport?.y || 0) +
														(10 +
															((componentViewport?.height || 200) - 24 - 34) /
																2) +
														0 +
														1 +
														0,
												},
												Ojr4RjW9Y: {
													height: 36,
													y:
														(componentViewport?.y || 0) +
														(10 +
															((componentViewport?.height || 200) - 24 - 54) /
																2) +
														0 +
														9 +
														0,
												},
												QuqZu40Aj: {
													height: 36,
													y:
														(componentViewport?.y || 0) +
														(10 +
															((componentViewport?.height || 66) - 24 - 54) /
																2) +
														0 +
														9 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-33h2jm-container"}
											layoutDependency={layoutDependency}
											layoutId={"hQ1bXVLLl-container"}
											nodeId={"hQ1bXVLLl"}
											rendersWithMotion={true}
											scopeId={"jkTp0PN3r"}
										>
											{_jsx(stdin_default2, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "hQ1bXVLLl",
												layoutId: "hQ1bXVLLl",
												style: {
													height: "100%",
												},
												variant: matchVariant("NrjywPsq8"),
												width: "100%",
												...addPropertyOverrides(
													{
														fCyPYonB5: {
															uDK4ahqml: uDK4ahqml1hoz6s,
														},
														Ojr4RjW9Y: {
															uDK4ahqml: uDK4ahqmlf6m6lj,
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								{isDisplayed() && (
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-mtbx3v"}
										data-framer-name={"Center"}
										layoutDependency={layoutDependency}
										layoutId={"dLfWgn1bu"}
										style={{
											backgroundColor: "rgba(0, 0, 0, 0)",
										}}
										variants={{
											fCyPYonB5: {
												backgroundColor:
													"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
											},
											Ojr4RjW9Y: {
												backgroundColor:
													"var(--token-3c675309-91c5-4b64-a956-9189118d694b, rgb(244, 240, 229))",
											},
										}}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1gmb2ft"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"MhXF33U8i"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													fCyPYonB5: {
														"data-highlight": true,
														onTap: onTap1hoz6s,
													},
													Ojr4RjW9Y: {
														"data-highlight": true,
														onTap: onTapf6m6lj,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-bzg784"}
													data-styles-preset={"xCP4A9yeH"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={{
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"MhXF33U8i"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"jkTp0PN3r"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-eke6e"}
															data-styles-preset={"G1RYAq02C"}
														>
															{"Home"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-16vhzhe"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"mwYANkYSA"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													fCyPYonB5: {
														"data-highlight": true,
														onTap: onTap1hoz6s,
													},
													Ojr4RjW9Y: {
														"data-highlight": true,
														onTap: onTapf6m6lj,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-bzg784"}
													data-styles-preset={"xCP4A9yeH"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={"/about"}
														motionChild={true}
														nodeId={"mwYANkYSA"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"jkTp0PN3r"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-eke6e"}
															data-styles-preset={"G1RYAq02C"}
														>
															{"About"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-r7lwo6"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"sAYLh6391"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													fCyPYonB5: {
														"data-highlight": true,
														onTap: onTap1hoz6s,
													},
													Ojr4RjW9Y: {
														"data-highlight": true,
														onTap: onTapf6m6lj,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-bzg784"}
													data-styles-preset={"xCP4A9yeH"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={{
															webPageId: "Zb8AJO2M5",
														}}
														motionChild={true}
														nodeId={"sAYLh6391"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"jkTp0PN3r"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-eke6e"}
															data-styles-preset={"G1RYAq02C"}
														>
															{"Program"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-4zh0jl"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ChbRYnBQq"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													fCyPYonB5: {
														"data-highlight": true,
														onTap: onTap1hoz6s,
													},
													Ojr4RjW9Y: {
														"data-highlight": true,
														onTap: onTapf6m6lj,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-bzg784"}
													data-styles-preset={"xCP4A9yeH"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={{
															webPageId: "JtLwS9TeY",
														}}
														motionChild={true}
														nodeId={"ChbRYnBQq"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"jkTp0PN3r"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-eke6e"}
															data-styles-preset={"G1RYAq02C"}
														>
															{"Mentor"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-hx7r5v"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"X4cGwlN3d"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													fCyPYonB5: {
														"data-highlight": true,
														onTap: onTap1hoz6s,
													},
													Ojr4RjW9Y: {
														"data-highlight": true,
														onTap: onTapf6m6lj,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-bzg784"}
													data-styles-preset={"xCP4A9yeH"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={"/contact"}
														motionChild={true}
														nodeId={"X4cGwlN3d"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"jkTp0PN3r"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-eke6e"}
															data-styles-preset={"G1RYAq02C"}
														>
															{"Contact"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								)}
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1edkcy3"}
									data-framer-name={"Right"}
									layoutDependency={layoutDependency}
									layoutId={"NC8mnSrkp"}
								>
									{isDisplayed1() && (
										<ResolveLinks
											suppressHydrationWarning={true}
											links={[
												{
													href: {
														webPageId: "peTwLqil9",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "peTwLqil9",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "peTwLqil9",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={54}
													y={
														(componentViewport?.y || 0) +
														(20 +
															((componentViewport?.height || 86) - 40 - 54) /
																2) +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															Ojr4RjW9Y: {
																y:
																	(componentViewport?.y || 0) +
																	(10 +
																		((componentViewport?.height || 200) -
																			24 -
																			54) /
																			2) +
																	0 +
																	0 +
																	0,
															},
															QuqZu40Aj: {
																y:
																	(componentViewport?.y || 0) +
																	(10 +
																		((componentViewport?.height || 66) -
																			24 -
																			54) /
																			2) +
																	0 +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-wpvdnk-container"}
														layoutDependency={layoutDependency}
														layoutId={"mU23Zsfvd-container"}
														nodeId={"mU23Zsfvd"}
														rendersWithMotion={true}
														scopeId={"jkTp0PN3r"}
													>
														{_jsx(stdin_default, {
															suppressHydrationWarning: true,
															height: "100%",
															id: "mU23Zsfvd",
															Kiib3s3Y3: "Get started",
															layoutId: "mU23Zsfvd",
															toG7h_P8o: resolvedLinks[0],
															variant: matchVariant("NrIRu2ZyU"),
															width: "100%",
															Y5KJgXrXk: false,
															...addPropertyOverrides(
																{
																	Ojr4RjW9Y: {
																		toG7h_P8o: resolvedLinks[2],
																		variant: matchVariant("HBtQ1oy6V"),
																	},
																	QuqZu40Aj: {
																		toG7h_P8o: resolvedLinks[1],
																		variant: matchVariant("HBtQ1oy6V"),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									)}
									{isDisplayed2() && (
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-gh64he"}
											data-border={true}
											data-framer-name={"Menu Button"}
											layoutDependency={layoutDependency}
											layoutId={"cKLtAj5aZ"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-a225ace6-638e-469b-9793-3ab54fcf3b3a, rgb(27, 52, 40))",
												borderBottomLeftRadius: "50%",
												borderBottomRightRadius: "50%",
												borderTopLeftRadius: "50%",
												borderTopRightRadius: "50%",
												boxShadow:
													"0px 3px 0px 0px var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
											}}
											{...addPropertyOverrides(
												{
													fCyPYonB5: {
														"data-highlight": true,
														onTap: onTap1hoz6s,
													},
													gAxzkC4Cq: {
														"data-highlight": true,
														onTap: onTap19kykfp,
													},
													Ojr4RjW9Y: {
														"data-highlight": true,
														onTap: onTapf6m6lj,
													},
													QuqZu40Aj: {
														"data-highlight": true,
														onTap: onTap1h55cr,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1babm8w"}
												data-framer-name={"01"}
												layoutDependency={layoutDependency}
												layoutId={"jWMDnmp6f"}
												style={{
													backgroundColor:
														"var(--token-7bbaafe9-06f3-4286-8b9e-1f6b96128a55, rgb(255, 255, 255))",
													borderBottomLeftRadius: 2,
													borderBottomRightRadius: 2,
													borderTopLeftRadius: 2,
													borderTopRightRadius: 2,
													rotate: 0,
												}}
												variants={{
													fCyPYonB5: {
														rotate: -45,
													},
													gAxzkC4Cq: {
														rotate: 0,
													},
													Ojr4RjW9Y: {
														rotate: -45,
													},
												}}
											/>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1vtahdq"}
												data-framer-name={"02"}
												layoutDependency={layoutDependency}
												layoutId={"sb0I4koOh"}
												style={{
													backgroundColor:
														"var(--token-7bbaafe9-06f3-4286-8b9e-1f6b96128a55, rgb(255, 255, 255))",
													borderBottomLeftRadius: 2,
													borderBottomRightRadius: 2,
													borderTopLeftRadius: 2,
													borderTopRightRadius: 2,
													rotate: 0,
												}}
												variants={{
													fCyPYonB5: {
														rotate: 45,
													},
													gAxzkC4Cq: {
														rotate: 0,
													},
													Ojr4RjW9Y: {
														rotate: 45,
													},
												}}
											/>
										</motion.div>
									)}
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-hd3rle"}
							data-framer-name={"Overlay"}
							layoutDependency={layoutDependency}
							layoutId={"GGT3VDTKJ"}
							style={{
								backgroundColor:
									"var(--token-864efae0-958b-4f0c-94c1-0e67aaf77b9c, rgba(20, 38, 29, 0.5))",
								opacity: 0,
							}}
							variants={{
								fCyPYonB5: {
									opacity: 1,
								},
								Ojr4RjW9Y: {
									opacity: 1,
								},
							}}
							{...addPropertyOverrides(
								{
									fCyPYonB5: {
										"data-highlight": true,
										onTap: onTap1hoz6s,
									},
									Ojr4RjW9Y: {
										"data-highlight": true,
										onTap: onTapf6m6lj,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	".framer-ahWi0.framer-s5f65k, .framer-ahWi0 .framer-s5f65k { display: block; }",
	".framer-ahWi0.framer-1q36u8u { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 20px 0px 20px 0px; position: relative; width: 1200px; }",
	".framer-ahWi0 .framer-1r5rn89 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 1px; z-index: 2; }",
	".framer-ahWi0 .framer-1s4y7z3 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 100px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ahWi0 .framer-82g7t8 { align-content: center; align-items: center; display: flex; flex: 0.5 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ahWi0 .framer-33h2jm-container { flex: none; height: 32px; position: relative; width: auto; }",
	".framer-ahWi0 .framer-mtbx3v { align-content: center; align-items: center; display: flex; flex: 1.5 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ahWi0 .framer-1gmb2ft, .framer-ahWi0 .framer-16vhzhe, .framer-ahWi0 .framer-r7lwo6, .framer-ahWi0 .framer-4zh0jl, .framer-ahWi0 .framer-hx7r5v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ahWi0 .framer-1edkcy3 { align-content: center; align-items: center; display: flex; flex: 0.5 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ahWi0 .framer-wpvdnk-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-ahWi0 .framer-gh64he { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: auto; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 42px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ahWi0 .framer-1babm8w, .framer-ahWi0 .framer-1vtahdq { flex: none; height: 2px; overflow: hidden; position: relative; width: 22px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ahWi0 .framer-hd3rle { -webkit-user-select: none; flex: none; height: calc(var(--framer-viewport-height, 100vh) * 1); left: calc(50.00000000000002% - 100% / 2); overflow: visible; pointer-events: none; position: absolute; top: calc(360.3603603603604% - 100vh / 2); user-select: none; width: 100%; }",
	".framer-ahWi0.framer-v-40idda.framer-1q36u8u, .framer-ahWi0.framer-v-8ikj6b.framer-1q36u8u { padding: 10px 0px 14px 0px; width: 810px; }",
	".framer-ahWi0.framer-v-40idda .framer-1r5rn89, .framer-ahWi0.framer-v-8ikj6b .framer-1r5rn89 { z-index: 1; }",
	".framer-ahWi0.framer-v-40idda .framer-82g7t8 { align-content: flex-start; align-items: flex-start; flex: 1 0 0px; }",
	".framer-ahWi0.framer-v-40idda .framer-33h2jm-container, .framer-ahWi0.framer-v-8ikj6b .framer-33h2jm-container { height: 36px; }",
	".framer-ahWi0.framer-v-40idda .framer-1edkcy3 { flex: 1 0 0px; }",
	".framer-ahWi0.framer-v-40idda .framer-wpvdnk-container, .framer-ahWi0.framer-v-40idda .framer-gh64he, .framer-ahWi0.framer-v-8ikj6b .framer-1gmb2ft, .framer-ahWi0.framer-v-8ikj6b .framer-16vhzhe, .framer-ahWi0.framer-v-8ikj6b .framer-r7lwo6, .framer-ahWi0.framer-v-8ikj6b .framer-4zh0jl, .framer-ahWi0.framer-v-8ikj6b .framer-hx7r5v, .framer-ahWi0.framer-v-8ikj6b .framer-wpvdnk-container, .framer-ahWi0.framer-v-8ikj6b .framer-gh64he, .framer-ahWi0.framer-v-jhl8yh .framer-1gmb2ft, .framer-ahWi0.framer-v-jhl8yh .framer-16vhzhe, .framer-ahWi0.framer-v-jhl8yh .framer-r7lwo6, .framer-ahWi0.framer-v-jhl8yh .framer-4zh0jl, .framer-ahWi0.framer-v-jhl8yh .framer-hx7r5v { cursor: pointer; }",
	".framer-ahWi0.framer-v-40idda .framer-1babm8w, .framer-ahWi0.framer-v-40idda .framer-1vtahdq { -webkit-user-select: none; pointer-events: none; user-select: none; }",
	".framer-ahWi0.framer-v-40idda .framer-hd3rle, .framer-ahWi0.framer-v-gs5urc .framer-hd3rle { top: 90px; }",
	".framer-ahWi0.framer-v-8ikj6b .framer-1s4y7z3 { z-index: 2; }",
	".framer-ahWi0.framer-v-8ikj6b .framer-mtbx3v { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; gap: 14px; justify-content: flex-start; left: -30px; padding: 14px 30px 14px 30px; position: absolute; right: -30px; top: 54px; width: unset; z-index: 2; }",
	".framer-ahWi0.framer-v-8ikj6b .framer-1babm8w, .framer-ahWi0.framer-v-8ikj6b .framer-1vtahdq { left: calc(50.00000000000002% - 20px / 2); position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 20px; z-index: 1; }",
	".framer-ahWi0.framer-v-8ikj6b .framer-hd3rle, .framer-ahWi0.framer-v-jhl8yh .framer-hd3rle { -webkit-user-select: auto; cursor: pointer; left: 0px; pointer-events: auto; right: 0px; top: 90px; user-select: auto; width: unset; }",
	".framer-ahWi0.framer-v-gs5urc.framer-1q36u8u, .framer-ahWi0.framer-v-jhl8yh.framer-1q36u8u { padding: 10px 0px 14px 0px; width: 390px; }",
	".framer-ahWi0.framer-v-gs5urc .framer-1r5rn89, .framer-ahWi0.framer-v-jhl8yh .framer-1r5rn89 { padding: 0px 20px 0px 20px; z-index: 1; }",
	".framer-ahWi0.framer-v-gs5urc .framer-82g7t8 { align-content: flex-start; align-items: flex-start; }",
	".framer-ahWi0.framer-v-gs5urc .framer-gh64he { aspect-ratio: unset; cursor: pointer; height: 34px; width: 34px; }",
	".framer-ahWi0.framer-v-gs5urc .framer-1babm8w, .framer-ahWi0.framer-v-gs5urc .framer-1vtahdq { width: 16px; }",
	".framer-ahWi0.framer-v-jhl8yh .framer-mtbx3v { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; gap: 10px; justify-content: flex-start; left: -20px; padding: 20px; position: absolute; right: -20px; top: 48px; width: unset; z-index: 2; }",
	".framer-ahWi0.framer-v-jhl8yh .framer-gh64he { cursor: pointer; width: 34px; }",
	".framer-ahWi0.framer-v-jhl8yh .framer-1babm8w, .framer-ahWi0.framer-v-jhl8yh .framer-1vtahdq { left: calc(50.00000000000002% - 16px / 2); position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 16px; z-index: 1; }",
	...css2,
	...css,
	'.framer-ahWi0[data-border="true"]::after, .framer-ahWi0 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerjkTp0PN3r = withCSS(Component, css3, "framer-ahWi0");
var stdin_default3 = FramerjkTp0PN3r;
FramerjkTp0PN3r.displayName = "Navigation";
FramerjkTp0PN3r.defaultProps = {
	height: 86,
	width: 1200,
};
addPropertyControls(FramerjkTp0PN3r, {
	variant: {
		options: ["XNilpKObr", "QuqZu40Aj", "Ojr4RjW9Y", "gAxzkC4Cq", "fCyPYonB5"],
		optionTitles: [
			"Desktop",
			"Tablet - Close",
			"Tablet - Open",
			"Phone - Close",
			"Phone - Open",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerjkTp0PN3r,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BrandLogoFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerjkTp0PN3r.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
