// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-EPDNPLDL.js";
import { stdin_default } from "./chunks/chunk-T5QRFJTY.js";
import "./chunks/chunk-R5PSICTC.js";
import "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:pricing-section-4-fa-qs
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gbZAl95LI7B8C7PI6Skq/ULd1D3hKB7bOYKDOB0Kb/ulGwgSkWa.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var GeneralAccordionFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["m4S8iQXZY", "JrIxOWeBE", "M9F8SZGd4"];
var serializationHash = "framer-XzzNc";
var variantClassNames = {
	JrIxOWeBE: "framer-v-ye3uyd",
	m4S8iQXZY: "framer-v-1kvvjz6",
	M9F8SZGd4: "framer-v-19ic6ri",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var transition3 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "m4S8iQXZY",
	Phone: "M9F8SZGd4",
	Tablet: "JrIxOWeBE",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "m4S8iQXZY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "m4S8iQXZY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1kvvjz6",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"m4S8iQXZY"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								JrIxOWeBE: {
									"data-framer-name": "Tablet",
								},
								M9F8SZGd4: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-jdzir9"}
							data-framer-name={"FAQs"}
							layoutDependency={layoutDependency}
							layoutId={"hhnbr4QQ4"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1b5alri"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"lQ6lBQumI"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-asgn45"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"N2M4FBj27"}
								>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-jwfrc"}
										data-framer-name={"Title"}
										layoutDependency={layoutDependency}
										layoutId={"iPgcTO83o"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-vsxiga"}
											data-framer-name={"Heading"}
											layoutDependency={layoutDependency}
											layoutId={"fcj6bBHXz"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-lujovs"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"BEgXjtNj4"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-jcbbly"}
														data-styles-preset={"UXoQEMm1m"}
														dir={"auto"}
													>
														{"No"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-9jo6g3"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"DVL6XIahG"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-jcbbly"}
														data-styles-preset={"UXoQEMm1m"}
														dir={"auto"}
													>
														{"stress,"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-11194ny"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"n67rAcdWT"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-jcbbly"}
														data-styles-preset={"UXoQEMm1m"}
														dir={"auto"}
													>
														{"no"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1dyodn8"}
												data-framer-name={"Highlight"}
												layoutDependency={layoutDependency}
												layoutId={"etNMu88PH"}
											>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-15abmt1"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"tMz0t3CSi"}
													style={{
														"--extracted-1of0zx5":
															"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
														rotate: 5,
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.h2
															suppressHydrationWarning={true}
															className={"framer-styles-preset-jcbbly"}
															data-styles-preset={"UXoQEMm1m"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100)))",
															}}
														>
															{"surprises"}
														</motion.h2>
													</React.Fragment>
												</RichText>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 34,
														intrinsicWidth: 33,
														pixelHeight: 34,
														pixelWidth: 33,
														sizes: "32px",
														src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
													}}
													className={"framer-4ac39l"}
													data-framer-name={"Top Decor"}
													layoutDependency={layoutDependency}
													layoutId={"WyD2B9UHt"}
												/>
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "stretch",
														intrinsicHeight: 46,
														intrinsicWidth: 219,
														pixelHeight: 46,
														pixelWidth: 219,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/JrJVDghR4XSfM4fEkVG4YlBTu0E.svg?width=219&height=46",
													}}
													className={"framer-1k1scdx"}
													data-framer-name={"Bottom Decor"}
													layoutDependency={layoutDependency}
													layoutId={"n8di16FaE"}
												/>
											</motion.div>
										</motion.div>
									</MotionDivWithFX>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition3,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1l5v4oz"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"CeUjf3kqD"}
									>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={563}
											width={`min(min(${componentViewport?.width || "100vw"}, 1460px) - 60px, 700px)`}
											{...addPropertyOverrides(
												{
													M9F8SZGd4: {
														width: `min(min(${componentViewport?.width || "100vw"}, 1460px) - 40px, 700px)`,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												suppressHydrationWarning={true}
												__framer__animate={{
													transition: transition3,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__exit={animation2}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-160dwf3-container"}
												layoutDependency={layoutDependency}
												layoutId={"G_OT5urlD-container"}
												nodeId={"G_OT5urlD"}
												rendersWithMotion={true}
												scopeId={"ulGwgSkWa"}
											>
												{_jsx(stdin_default, {
													suppressHydrationWarning: true,
													cSEHqsEip:
														"Yes, no lock-in, no fees. You can pause for up to 30 days or cancel anytime. Just give us 24 hours' notice before your next scheduled session and we'll handle everything for you.",
													Fymv0_Zvc: "Can we pause or cancel anytime?",
													H6bBZRZOD:
														"A 45-minute session where a mentor gets to know you, finds the right starting level, and builds a personal plan. You keep the plan whether you sign up or not.",
													height: "100%",
													id: "G_OT5urlD",
													IXxCcNeJ6: "How do you track progress?",
													iz8dLER8f: "How does the free first session work?",
													layoutId: "G_OT5urlD",
													Q4ZZO31fL:
														"After each session your mentor logs notes and milestones reached. You'll see a clear summary in your dashboard, and your mentor will review it with you at the start of every next session.",
													style: {
														width: "100%",
													},
													Ud8d5BBpu: "One-on-one or group, which is better?",
													UKJn2h870: "Who are the mentors?",
													variant: matchVariant("qTuhmXSEb"),
													wdAkIO5Do:
														"One-on-one gives you a pace and plan built entirely around you, while group sessions add peer energy at a lower cost. Your mentor will recommend the best fit after the free first session.",
													width: "100%",
													x_pLEqbCc:
														"All mentors are vetted educators with subject expertise and at least two years of teaching experience. They go through structured onboarding and receive regular feedback to keep quality high.",
													...addPropertyOverrides(
														{
															M9F8SZGd4: {
																variant: matchVariant("Kd9nLiht9"),
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
									</MotionDivWithFX>
								</motion.div>
							</motion.div>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	".framer-XzzNc.framer-125avtl, .framer-XzzNc .framer-125avtl { display: block; }",
	".framer-XzzNc.framer-1kvvjz6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-XzzNc .framer-jdzir9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 150px 0px 150px 0px; position: relative; width: 100%; }",
	".framer-XzzNc .framer-1b5alri { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-XzzNc .framer-asgn45 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-XzzNc .framer-jwfrc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-XzzNc .framer-vsxiga { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: wrap; gap: 0px 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-XzzNc .framer-lujovs, .framer-XzzNc .framer-9jo6g3, .framer-XzzNc .framer-11194ny, .framer-XzzNc .framer-15abmt1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-XzzNc .framer-1dyodn8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 26px 0px; position: relative; width: min-content; }",
	".framer-XzzNc .framer-4ac39l { -webkit-user-select: none; aspect-ratio: 1.032258064516129 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 32px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-XzzNc .framer-1k1scdx { -webkit-user-select: none; bottom: 0px; flex: none; height: 44px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-XzzNc .framer-1l5v4oz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; max-width: 700px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-XzzNc .framer-160dwf3-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-XzzNc.framer-v-ye3uyd.framer-1kvvjz6 { width: 810px; }",
	".framer-XzzNc.framer-v-ye3uyd .framer-jdzir9 { padding: 100px 0px 100px 0px; }",
	".framer-XzzNc.framer-v-ye3uyd .framer-asgn45 { gap: 40px; }",
	".framer-XzzNc.framer-v-19ic6ri.framer-1kvvjz6 { width: 390px; }",
	".framer-XzzNc.framer-v-19ic6ri .framer-jdzir9 { padding: 80px 0px 80px 0px; }",
	".framer-XzzNc.framer-v-19ic6ri .framer-1b5alri { padding: 0px 20px 0px 20px; }",
	".framer-XzzNc.framer-v-19ic6ri .framer-asgn45 { gap: 30px; }",
	".framer-XzzNc.framer-v-19ic6ri .framer-vsxiga { gap: 0px 8px; }",
	...css,
];
var FramerulGwgSkWa = withCSS(Component, css2, "framer-XzzNc");
var stdin_default2 = FramerulGwgSkWa;
FramerulGwgSkWa.displayName = "Pricing Section 4 \u2014 FAQs";
FramerulGwgSkWa.defaultProps = {
	height: 1029,
	width: 1200,
};
addPropertyControls(FramerulGwgSkWa, {
	variant: {
		options: ["m4S8iQXZY", "JrIxOWeBE", "M9F8SZGd4"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerulGwgSkWa,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...GeneralAccordionFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerulGwgSkWa.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:pricing-section-4-fa-qs
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricingSection4FaQsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var pricing_section_4_fa_qs_default = ComponentWithRoot;
export { pricing_section_4_fa_qs_default as default };
