// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className9,
	css as css9,
	fonts as fonts9,
} from "./chunks/chunk-EFVIXQYH.js";
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-MLB3MC5T.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-AOWK4JFD.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-4XRGEVGL.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-6ONBAXWQ.js";
import {
	className as className8,
	css as css8,
	fonts as fonts8,
} from "./chunks/chunk-EPDNPLDL.js";
import { className, css, fonts } from "./chunks/chunk-RFLCCK3R.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-R5PSICTC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:program-detail-section-2-course
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rYEW6MuY3TtJkGlqJUcx/F6HnVm9DdGlAb1JooH7b/hljflaiWZ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var RichTextWithFX = withFX(RichText);
var cycleOrder = ["uwpS0Gkjg", "CbhxdnIYC", "aSQLZukll"];
var serializationHash = "framer-hRL4t";
var variantClassNames = {
	aSQLZukll: "framer-v-1uau3oz",
	CbhxdnIYC: "framer-v-1b1kw9a",
	uwpS0Gkjg: "framer-v-1gkxiao",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var AlYJU3rfdfdu0v1MtY = void 0;
var Atet3qL3Ufdu0v1MtY = void 0;
var WKiK9v9LCfdu0v1MtY = void 0;
var B3GrEvcRffdu0v1MtY = void 0;
var o2t1Enj0mfdu0v1MtY = void 0;
var ym1ibWGrdfdu0v1MtY = void 0;
var DoMyhitd7fdu0v1MtY = void 0;
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var transition3 = {
	delay: 0.3,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var transition4 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 30,
};
var transition5 = {
	delay: 0.5,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 30,
};
var transition6 = {
	delay: 0.6,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation5 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 30,
};
var transition7 = {
	delay: 0.7,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation6 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 30,
};
var transition8 = {
	delay: 0.8,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation7 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition8,
	x: 0,
	y: 30,
};
var transition9 = {
	delay: 0.9,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation8 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition9,
	x: 0,
	y: 30,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "uwpS0Gkjg",
	Phone: "aSQLZukll",
	Tablet: "CbhxdnIYC",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "uwpS0Gkjg",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className10,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uwpS0Gkjg",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className8,
		className5,
		className6,
		className4,
		className3,
		className7,
		className9,
		className,
		className2,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(AlYJU3rfdfdu0v1MtY);
	const visible1 = isSet(Atet3qL3Ufdu0v1MtY);
	const visible2 = isSet(WKiK9v9LCfdu0v1MtY);
	const visible3 = isSet(B3GrEvcRffdu0v1MtY);
	const visible4 = isSet(o2t1Enj0mfdu0v1MtY);
	const visible5 = isSet(ym1ibWGrdfdu0v1MtY);
	const visible6 = isSet(DoMyhitd7fdu0v1MtY);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1gkxiao",
							className10,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"uwpS0Gkjg"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								aSQLZukll: {
									"data-framer-name": "Phone",
								},
								CbhxdnIYC: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-p67mzk"}
							data-framer-name={"Course"}
							layoutDependency={layoutDependency}
							layoutId={"fEex90NZd"}
							style={{
								backgroundColor:
									"var(--token-e079c459-c6e9-4577-8c52-a24b838cfa37, rgb(234, 228, 211))",
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1mbezns"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"c9dJDHO_J"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1feh5e0"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"gBgZFyQaM"}
								>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-wj8bel"}
										data-framer-name={"Heading"}
										layoutDependency={layoutDependency}
										layoutId={"XcbXIBv6j"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-4skc1h"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"oJEo1U163"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h2
													suppressHydrationWarning={true}
													className={"framer-styles-preset-jcbbly"}
													data-styles-preset={"UXoQEMm1m"}
													dir={"auto"}
												>
													{"What's"}
												</motion.h2>
											</React.Fragment>
										</RichText>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-7l2iya"}
											data-framer-name={"Highlight"}
											layoutDependency={layoutDependency}
											layoutId={"pbZozTgwE"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1tkbhch"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"C5avbPoHU"}
												style={{
													"--extracted-1of0zx5":
														"var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
													rotate: 5,
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														suppressHydrationWarning={true}
														className={"framer-styles-preset-jcbbly"}
														data-styles-preset={"UXoQEMm1m"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-1d403a9e-a47a-49fa-b259-3726165583a7, rgb(73, 126, 100)))",
														}}
													>
														{"covered"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<Image1
												suppressHydrationWarning={true}
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 34,
													intrinsicWidth: 33,
													pixelHeight: 34,
													pixelWidth: 33,
													sizes: "32px",
													src: "https://framerusercontent.com/images/AKsn6ZsWzZYFuQbOLWjDXQOBfU.svg?width=33&height=34",
												}}
												className={"framer-1xzv87y"}
												data-framer-name={"Top Decor"}
												layoutDependency={layoutDependency}
												layoutId={"niRfE_uvG"}
											/>
											<Image1
												suppressHydrationWarning={true}
												background={{
													alt: "",
													fit: "stretch",
													intrinsicHeight: 46,
													intrinsicWidth: 219,
													pixelHeight: 46,
													pixelWidth: 219,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/JrJVDghR4XSfM4fEkVG4YlBTu0E.svg?width=219&height=46",
												}}
												className={"framer-fq87d1"}
												data-framer-name={"Bottom Decor"}
												layoutDependency={layoutDependency}
												layoutId={"hLU4qQ0ED"}
											/>
										</motion.div>
									</MotionDivWithFX>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1tjso2o"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"IBJNKpBpB"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-bm0lqc"}
											data-framer-name={"TOP"}
											layoutDependency={layoutDependency}
											layoutId={"Dkub5flBb"}
										>
											{visible !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition3,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation2}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-m0wj33"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"xhljfTd9e"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-1bljwt9",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{AlYJU3rfdfdu0v1MtY}
												</RichTextWithFX>
											)}
											{visible1 !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition4,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation3}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-ujo849"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"ML3cp7CYL"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-1bljwt9",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{Atet3qL3Ufdu0v1MtY}
												</RichTextWithFX>
											)}
											{visible2 !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition5,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation4}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-ehrfio"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"jrE0gEVdD"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-1bljwt9",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{WKiK9v9LCfdu0v1MtY}
												</RichTextWithFX>
											)}
											{visible3 !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition6,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation5}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-4bvctr"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"wITAUp5vz"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-1bljwt9",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{B3GrEvcRffdu0v1MtY}
												</RichTextWithFX>
											)}
										</motion.div>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1k8sq9"}
											data-framer-name={"Bottom"}
											layoutDependency={layoutDependency}
											layoutId={"cvsjNh_My"}
										>
											{visible4 !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition7,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation6}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-84qxnz"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"sQxwiiQPu"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-1bljwt9",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{o2t1Enj0mfdu0v1MtY}
												</RichTextWithFX>
											)}
											{visible5 !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition8,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation7}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-n9pyak"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"z_g9wSKUv"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-1bljwt9",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{ym1ibWGrdfdu0v1MtY}
												</RichTextWithFX>
											)}
											{visible6 !== false && (
												<RichTextWithFX
													suppressHydrationWarning={true}
													__framer__animate={{
														transition: transition9,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__exit={animation8}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0}
													__fromCanvasComponent={true}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-1r1h0g0"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"npCKg_ua0"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-7580yq",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{DoMyhitd7fdu0v1MtY}
												</RichTextWithFX>
											)}
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css10 = [
	".framer-hRL4t.framer-pxhhdt, .framer-hRL4t .framer-pxhhdt { display: block; }",
	".framer-hRL4t.framer-1gkxiao { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-hRL4t .framer-p67mzk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 150px 0px 150px 0px; position: relative; width: 100%; }",
	".framer-hRL4t .framer-1mbezns { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-hRL4t .framer-1feh5e0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hRL4t .framer-wj8bel { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 12px; height: min-content; justify-content: center; max-width: 860px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hRL4t .framer-4skc1h, .framer-hRL4t .framer-1tkbhch { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-hRL4t .framer-7l2iya { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 26px 0px; position: relative; width: min-content; }",
	".framer-hRL4t .framer-1xzv87y { -webkit-user-select: none; aspect-ratio: 1 / 1; flex: none; height: auto; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 32px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-hRL4t .framer-fq87d1 { -webkit-user-select: none; bottom: 0px; flex: none; height: 44px; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; user-select: none; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-hRL4t .framer-1tjso2o { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hRL4t .framer-bm0lqc, .framer-hRL4t .framer-1k8sq9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hRL4t .framer-m0wj33, .framer-hRL4t .framer-ujo849, .framer-hRL4t .framer-ehrfio, .framer-hRL4t .framer-4bvctr, .framer-hRL4t .framer-84qxnz, .framer-hRL4t .framer-n9pyak, .framer-hRL4t .framer-1r1h0g0 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-hRL4t.framer-v-1b1kw9a.framer-1gkxiao { width: 810px; }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-p67mzk { padding: 100px 0px 100px 0px; }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-1feh5e0 { gap: 40px; }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-bm0lqc { align-content: unset; align-items: unset; display: grid; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-m0wj33, .framer-hRL4t.framer-v-1b1kw9a .framer-ujo849, .framer-hRL4t.framer-v-1b1kw9a .framer-ehrfio, .framer-hRL4t.framer-v-1b1kw9a .framer-4bvctr, .framer-hRL4t.framer-v-1uau3oz .framer-m0wj33, .framer-hRL4t.framer-v-1uau3oz .framer-ujo849, .framer-hRL4t.framer-v-1uau3oz .framer-ehrfio, .framer-hRL4t.framer-v-1uau3oz .framer-4bvctr { align-self: start; flex: none; height: 100%; justify-self: start; width: 100%; }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-1k8sq9 { align-content: unset; align-items: unset; display: grid; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-84qxnz, .framer-hRL4t.framer-v-1b1kw9a .framer-n9pyak, .framer-hRL4t.framer-v-1uau3oz .framer-84qxnz, .framer-hRL4t.framer-v-1uau3oz .framer-n9pyak { align-self: start; flex: none; justify-self: start; width: 100%; }",
	".framer-hRL4t.framer-v-1b1kw9a .framer-1r1h0g0 { align-self: start; flex: none; grid-column: span 2; justify-self: start; width: 100%; }",
	".framer-hRL4t.framer-v-1uau3oz.framer-1gkxiao { width: 390px; }",
	".framer-hRL4t.framer-v-1uau3oz .framer-p67mzk { padding: 80px 0px 80px 0px; }",
	".framer-hRL4t.framer-v-1uau3oz .framer-1mbezns { padding: 0px 20px 0px 20px; }",
	".framer-hRL4t.framer-v-1uau3oz .framer-1feh5e0 { gap: 30px; }",
	".framer-hRL4t.framer-v-1uau3oz .framer-wj8bel { gap: 0px 8px; }",
	".framer-hRL4t.framer-v-1uau3oz .framer-1tjso2o { gap: 50px; }",
	".framer-hRL4t.framer-v-1uau3oz .framer-bm0lqc { align-content: unset; align-items: unset; display: grid; gap: 20px; grid-auto-rows: min-content; grid-template-columns: repeat(1, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); }",
	".framer-hRL4t.framer-v-1uau3oz .framer-1k8sq9 { align-content: unset; align-items: unset; display: grid; gap: 20px; grid-auto-rows: min-content; grid-template-columns: repeat(1, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); }",
	".framer-hRL4t.framer-v-1uau3oz .framer-1r1h0g0 { align-self: start; flex: none; grid-column: span 1; justify-self: start; width: 100%; }",
	...css8,
	...css5,
	...css6,
	...css4,
	...css3,
	...css7,
	...css9,
	...css,
	...css2,
];
var FramerhljflaiWZ = withCSS(Component, css10, "framer-hRL4t");
var stdin_default = FramerhljflaiWZ;
FramerhljflaiWZ.displayName = "Program Detail Section 2 \u2014 Course";
FramerhljflaiWZ.defaultProps = {
	height: 200,
	width: 200,
};
addPropertyControls(FramerhljflaiWZ, {
	variant: {
		options: ["uwpS0Gkjg", "CbhxdnIYC", "aSQLZukll"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerhljflaiWZ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:program-detail-section-2-course
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProgramDetailSection2CourseFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var program_detail_section_2_course_default = ComponentWithRoot;
export { program_detail_section_2_course_default as default };


// --- unframer-cms-binding (generated by scripts/bind-cms.mjs) ---
export function __bindCmsFields(values) {
	if ("AlYJU3rfd" in values) AlYJU3rfdfdu0v1MtY = values["AlYJU3rfd"];
	if ("Atet3qL3U" in values) Atet3qL3Ufdu0v1MtY = values["Atet3qL3U"];
	if ("WKiK9v9LC" in values) WKiK9v9LCfdu0v1MtY = values["WKiK9v9LC"];
	if ("B3GrEvcRf" in values) B3GrEvcRffdu0v1MtY = values["B3GrEvcRf"];
	if ("o2t1Enj0m" in values) o2t1Enj0mfdu0v1MtY = values["o2t1Enj0m"];
	if ("ym1ibWGrd" in values) ym1ibWGrdfdu0v1MtY = values["ym1ibWGrd"];
	if ("DoMyhitd7" in values) DoMyhitd7fdu0v1MtY = values["DoMyhitd7"];
}
export const __cmsFieldIds = ["AlYJU3rfd","Atet3qL3U","WKiK9v9LC","B3GrEvcRf","o2t1Enj0m","ym1ibWGrd","DoMyhitd7"];
