// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-EFVIXQYH.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-3QLKY5XU.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-C7HLIECH.js";
import "./chunks/chunk-AOWK4JFD.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-6ONBAXWQ.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-6JHFWNKR.js";
import { stdin_default } from "./chunks/chunk-DPP5EL47.js";
import { className, css, fonts } from "./chunks/chunk-C742CGXR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:program-detail-section-1-hero
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/aWoaiahrzPScgtgAPNQe/Osld8icKxuiOiwIbLrRG/LZvKUrvDA.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Image as Image1,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var ButtonFonts = getFonts(stdin_default);
var InfoCardFonts = getFonts(stdin_default3);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var SectionDecorFonts = getFonts(stdin_default2);
var cycleOrder = ["HN6KdX4Ig", "kfh2W1SR5", "bK0E6Ygrl"];
var serializationHash = "framer-vzx6o";
var variantClassNames = {
	bK0E6Ygrl: "framer-v-1i8rxy6",
	HN6KdX4Ig: "framer-v-1i63swv",
	kfh2W1SR5: "framer-v-1ilxzzf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var bw5wYLxeb_QLObxbGfmfdu0v1MtY = void 0;
var hUvhbUSVSfdu0v1MtY = void 0;
var K6guXv55Ofdu0v1MtY = void 0;
var HNtd_VJxBfdu0v1MtY = void 0;
var TsxYJujxIfdu0v1MtY = void 0;
var gZLQKE2TDfdu0v1MtY = void 0;
var BuzbVg2cgfdu0v1MtY = void 0;
var XxkBqqz4Ufdu0v1MtY = void 0;
var QxkZWvI2zfdu0v1MtY = void 0;
var lNQa0DDFIfdu0v1MtY = void 0;
var mWtmbqNAtfdu0v1MtY = void 0;
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var transition3 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition4 = {
	delay: 0.35,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var transition5 = {
	delay: 0.5,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 0,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transition6 = {
	delay: 0.6,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 0,
};
var transition7 = {
	delay: 0.7,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation6 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 0,
};
var transition8 = {
	delay: 0.8,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation7 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition8,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "HN6KdX4Ig",
	Phone: "bK0E6Ygrl",
	Tablet: "kfh2W1SR5",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "HN6KdX4Ig",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HN6KdX4Ig",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className2,
		className5,
		className,
		className3,
		className4,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(bw5wYLxeb_QLObxbGfmfdu0v1MtY);
	const visible1 = isSet(K6guXv55Ofdu0v1MtY);
	const visible2 = isSet(HNtd_VJxBfdu0v1MtY);
	const visible3 = isSet(TsxYJujxIfdu0v1MtY);
	const router = useRouter();
	const visible4 = isSet(gZLQKE2TDfdu0v1MtY);
	const visible5 = isSet(XxkBqqz4Ufdu0v1MtY);
	const visible6 = isSet(lNQa0DDFIfdu0v1MtY);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1i63swv",
							className6,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"HN6KdX4Ig"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								bK0E6Ygrl: {
									"data-framer-name": "Phone",
								},
								kfh2W1SR5: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-14h3b8k"}
							data-framer-name={"Hero"}
							layoutDependency={layoutDependency}
							layoutId={"A1S8Tj0cH"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-i3tt6z"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"stgUUM6Ep"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1pqsmac"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"UMUpY_epE"}
								>
									<MotionDivWithFXWithOptimizedAppearEffect
										suppressHydrationWarning={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1jzk0t0"}
										data-framer-appear-id={"1jzk0t0"}
										data-framer-name={"Top"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"lObieZLVh"}
										optimized={true}
									>
										{visible !== false && (
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-i4m78n"}
												data-framer-name={"Tilte"}
												layoutDependency={layoutDependency}
												layoutId={"khkpZOeEb"}
											>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-xemop0"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"rCle5r5m8"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-7580yq"}
															data-styles-preset={"ESdyUGyJl"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
															}}
														>
															<Link
																suppressHydrationWarning={true}
																href={{
																	webPageId: "Zb8AJO2M5",
																}}
																motionChild={true}
																nodeId={"rCle5r5m8"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"LZvKUrvDA"}
																smoothScroll={false}
															>
																<motion.a
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-6bfe7n"}
																	data-styles-preset={"z21Fbw9Ms"}
																>
																	{"Program"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-4dowtn"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"m6L_np3Qo"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-7580yq"}
															data-styles-preset={"ESdyUGyJl"}
															dir={"auto"}
														>
															{"\u2192"}
														</motion.p>
													</React.Fragment>
												</RichText>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-1ir8olv"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"fRJux79Ys"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-a45bfe38-56a3-401b-9ec5-66a4a4243ef1, rgba(0, 0, 0, 0.56))",
													}}
													text={hUvhbUSVSfdu0v1MtY}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-7580yq"}
															data-styles-preset={"ESdyUGyJl"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a45bfe38-56a3-401b-9ec5-66a4a4243ef1, rgba(0, 0, 0, 0.56)))",
															}}
														>
															{"Mathematics"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										)}
									</MotionDivWithFXWithOptimizedAppearEffect>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-imaiz5"}
										data-framer-name={"Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"QoszLa7ih"}
									>
										<MotionDivWithFXWithOptimizedAppearEffect
											suppressHydrationWarning={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											animate={animation2}
											className={"framer-133zy5k"}
											data-framer-appear-id={"133zy5k"}
											data-framer-name={"Left"}
											initial={animation1}
											layoutDependency={layoutDependency}
											layoutId={"AiTr_NfHe"}
											optimized={true}
										>
											{visible1 !== false && (
												<Image1
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 550,
														intrinsicWidth: 590,
														pixelHeight: 550,
														pixelWidth: 590,
														sizes: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 140px) / 2.3, 1px)`,
														...toResponsiveImage(K6guXv55Ofdu0v1MtY),
													}}
													className={"framer-oen83t"}
													fitImageDimension={"height"}
													layoutDependency={layoutDependency}
													layoutId={"vQLpajKcJ"}
													style={{
														borderBottomLeftRadius: 20,
														borderBottomRightRadius: 20,
														borderTopLeftRadius: 20,
														borderTopRightRadius: 20,
													}}
													{...addPropertyOverrides(
														{
															bK0E6Ygrl: {
																background: {
																	alt: "",
																	fit: "fill",
																	intrinsicHeight: 550,
																	intrinsicWidth: 590,
																	pixelHeight: 550,
																	pixelWidth: 590,
																	sizes: `calc(min(${componentViewport?.width || "100vw"}, 1460px) - 40px)`,
																	...toResponsiveImage(K6guXv55Ofdu0v1MtY),
																},
															},
															kfh2W1SR5: {
																background: {
																	alt: "",
																	fit: "fill",
																	intrinsicHeight: 550,
																	intrinsicWidth: 590,
																	pixelHeight: 550,
																	pixelWidth: 590,
																	sizes: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 100px) / 2.3, 1px)`,
																	...toResponsiveImage(K6guXv55Ofdu0v1MtY),
																},
															},
														},
														baseVariant,
														gestureVariant,
													)}
												/>
											)}
											{visible2 !== false && (
												<motion.div
													suppressHydrationWarning={true}
													className={"framer-15xeqtc"}
													data-framer-name={"Badge"}
													layoutDependency={layoutDependency}
													layoutId={"j6vX7xF_2"}
													style={{
														rotate: 10.5,
													}}
												>
													{visible2 !== false && (
														<motion.div
															suppressHydrationWarning={true}
															className={"framer-kbctvr"}
															data-border={true}
															data-framer-name={"Level Badge"}
															layoutDependency={layoutDependency}
															layoutId={"l8QmKRGFs"}
															style={{
																"--border-bottom-width": "1px",
																"--border-color":
																	"var(--token-5bafd284-4248-4179-8fdd-7a454d5f3ef0, rgb(160, 175, 100))",
																"--border-left-width": "1px",
																"--border-right-width": "1px",
																"--border-style": "solid",
																"--border-top-width": "1px",
																backgroundColor:
																	"var(--token-e8cec243-b334-4568-a85b-a75cea534593, rgb(214, 229, 154))",
																borderBottomLeftRadius: 50,
																borderBottomRightRadius: 50,
																borderTopLeftRadius: 50,
																borderTopRightRadius: 50,
																boxShadow:
																	"3px 4px 0px 0px var(--token-5bafd284-4248-4179-8fdd-7a454d5f3ef0, rgb(160, 175, 100))",
															}}
														>
															<RichText
																suppressHydrationWarning={true}
																__fromCanvasComponent={true}
																className={"framer-fa5nr2"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"sJYviK6js"}
																style={{
																	"--extracted-r6o4lv":
																		"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
																}}
																text={HNtd_VJxBfdu0v1MtY}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		suppressHydrationWarning={true}
																		className={"framer-styles-preset-bzg784"}
																		data-styles-preset={"xCP4A9yeH"}
																		dir={"auto"}
																		style={{
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
																		}}
																	>
																		{"All levels"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.div>
													)}
												</motion.div>
											)}
										</MotionDivWithFXWithOptimizedAppearEffect>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1mex38g"}
											data-framer-name={"Right"}
											layoutDependency={layoutDependency}
											layoutId={"xU8aXN92G"}
										>
											<MotionDivWithFXWithOptimizedAppearEffect
												suppressHydrationWarning={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation3}
												className={"framer-utlr18"}
												data-framer-appear-id={"utlr18"}
												data-framer-name={"01"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"avYIQjFdB"}
												optimized={true}
											>
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-jxj3w7"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"cm_eoD4uE"}
													style={{
														"--extracted-gdpscs":
															"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
													}}
													text={hUvhbUSVSfdu0v1MtY}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.h1
															suppressHydrationWarning={true}
															className={"framer-styles-preset-1w1zhlt"}
															data-styles-preset={"c4bkaT15f"}
															dir={"auto"}
															style={{
																"--framer-text-alignment": "start",
																"--framer-text-color":
																	"var(--extracted-gdpscs, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
															}}
														>
															{"Mathematics"}
														</motion.h1>
													</React.Fragment>
												</RichText>
												{visible3 !== false && (
													<RichText
														suppressHydrationWarning={true}
														__fromCanvasComponent={true}
														className={"framer-t5azft"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"pILsTA53b"}
														text={TsxYJujxIfdu0v1MtY}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1bljwt9"}
																data-styles-preset={"qyxtvc7Ur"}
																dir={"auto"}
																style={{
																	"--framer-text-alignment": "start",
																}}
															>
																{
																	"We rebuild confidence first, then speed. From number sense to calculus, every learner gets a plan built around their actual gaps not a generic worksheet pile."
																}
															</motion.p>
														</React.Fragment>
													</RichText>
												)}
											</MotionDivWithFXWithOptimizedAppearEffect>
											<MotionDivWithFXWithOptimizedAppearEffect
												suppressHydrationWarning={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation4}
												className={"framer-js4v7e"}
												data-framer-appear-id={"js4v7e"}
												data-framer-name={"02"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"uBZXs169J"}
												optimized={true}
											>
												<ResolveLinks
													suppressHydrationWarning={true}
													links={[
														{
															href: {
																webPageId: "peTwLqil9",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "peTwLqil9",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "peTwLqil9",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks) => (
														<ComponentViewportProvider
															suppressHydrationWarning={true}
															height={54}
														>
															<SmartComponentScopedContainer
																suppressHydrationWarning={true}
																className={"framer-lrvwr5-container"}
																layoutDependency={layoutDependency}
																layoutId={"TNfQJO5_Z-container"}
																nodeId={"TNfQJO5_Z"}
																rendersWithMotion={true}
																scopeId={"LZvKUrvDA"}
															>
																{_jsx(stdin_default, {
																	suppressHydrationWarning: true,
																	height: "100%",
																	id: "TNfQJO5_Z",
																	Kiib3s3Y3: "Try a free session",
																	layoutId: "TNfQJO5_Z",
																	toG7h_P8o: resolvedLinks[0],
																	variant: matchVariant("EUoTryFDz"),
																	width: "100%",
																	Y5KJgXrXk: false,
																	...addPropertyOverrides(
																		{
																			bK0E6Ygrl: {
																				toG7h_P8o: resolvedLinks[2],
																				variant: matchVariant("ltttFCNrV"),
																			},
																			kfh2W1SR5: {
																				toG7h_P8o: resolvedLinks[1],
																				variant: matchVariant("ltttFCNrV"),
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													suppressHydrationWarning={true}
													links={[
														{
															href: {
																webPageId: "KqEuRPBiF",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "KqEuRPBiF",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "KqEuRPBiF",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks1) => (
														<ComponentViewportProvider
															suppressHydrationWarning={true}
															height={54}
														>
															<SmartComponentScopedContainer
																suppressHydrationWarning={true}
																className={"framer-1qco4zu-container"}
																layoutDependency={layoutDependency}
																layoutId={"aFW25qkhs-container"}
																nodeId={"aFW25qkhs"}
																rendersWithMotion={true}
																scopeId={"LZvKUrvDA"}
															>
																{_jsx(stdin_default, {
																	suppressHydrationWarning: true,
																	height: "100%",
																	id: "aFW25qkhs",
																	Kiib3s3Y3: "See pricing",
																	layoutId: "aFW25qkhs",
																	toG7h_P8o: resolvedLinks1[0],
																	variant: matchVariant("rXm6wdU1M"),
																	width: "100%",
																	Y5KJgXrXk: false,
																	...addPropertyOverrides(
																		{
																			bK0E6Ygrl: {
																				toG7h_P8o: resolvedLinks1[2],
																				variant: matchVariant("HcnRaMtkH"),
																			},
																			kfh2W1SR5: {
																				toG7h_P8o: resolvedLinks1[1],
																				variant: matchVariant("HcnRaMtkH"),
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
											</MotionDivWithFXWithOptimizedAppearEffect>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-1wseqrf"}
												data-framer-name={"03"}
												layoutDependency={layoutDependency}
												layoutId={"T55t5hEQo"}
											>
												{visible4 !== false && (
													<ComponentViewportProvider
														suppressHydrationWarning={true}
														height={0}
														width={`max((max((min(${componentViewport?.width || "100vw"}, 1460px) - 140px) * 0.5652, 1px) - 40px) / 3, 50px)`}
														{...addPropertyOverrides(
															{
																bK0E6Ygrl: {
																	width: `max(min(${componentViewport?.width || "100vw"}, 1460px) - 40px, 50px)`,
																},
																kfh2W1SR5: {
																	width: `max((max((min(${componentViewport?.width || "100vw"}, 1460px) - 100px) * 0.5652, 1px) - 20px) / 2, 50px)`,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															suppressHydrationWarning={true}
															__perspectiveFX={false}
															__smartComponentFX={true}
															__targetOpacity={1}
															animate={animation5}
															className={"framer-1wwrazi-container"}
															data-framer-appear-id={"1wwrazi"}
															initial={animation1}
															layoutDependency={layoutDependency}
															layoutId={"dkZyWqaSh-container"}
															nodeId={"dkZyWqaSh"}
															optimized={true}
															rendersWithMotion={true}
															scopeId={"LZvKUrvDA"}
														>
															{_jsx(stdin_default3, {
																suppressHydrationWarning: true,
																height: "100%",
																id: "dkZyWqaSh",
																layoutId: "dkZyWqaSh",
																Np9CObSKS: {
																	borderColor:
																		"var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178))",
																	borderStyle: "solid",
																	borderWidth: 1,
																},
																QXHcdXjw7:
																	"3px 4px 0px 0px var(--token-d46389a1-c11a-499f-a8d1-1f5543960045, rgb(84, 136, 178))",
																RQEvdrXW0: BuzbVg2cgfdu0v1MtY,
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: matchVariant("vOlkK4IVV"),
																width: "100%",
																z4hpWgaDr: gZLQKE2TDfdu0v1MtY,
																zNqg7GDkY:
																	"var(--token-78006fc2-4aed-468c-a9d5-0eb0993d6aea, rgb(201, 224, 242))",
																...addPropertyOverrides(
																	{
																		bK0E6Ygrl: {
																			variant: matchVariant("zpZ8Hyds8"),
																		},
																		kfh2W1SR5: {
																			variant: matchVariant("zpZ8Hyds8"),
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
												{visible5 !== false && (
													<ComponentViewportProvider
														suppressHydrationWarning={true}
														height={0}
														width={`max((max((min(${componentViewport?.width || "100vw"}, 1460px) - 140px) * 0.5652, 1px) - 40px) / 3, 50px)`}
														{...addPropertyOverrides(
															{
																bK0E6Ygrl: {
																	width: `max(min(${componentViewport?.width || "100vw"}, 1460px) - 40px, 50px)`,
																},
																kfh2W1SR5: {
																	width: `max((max((min(${componentViewport?.width || "100vw"}, 1460px) - 100px) * 0.5652, 1px) - 20px) / 2, 50px)`,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															suppressHydrationWarning={true}
															__perspectiveFX={false}
															__smartComponentFX={true}
															__targetOpacity={1}
															animate={animation6}
															className={"framer-193s4mq-container"}
															data-framer-appear-id={"193s4mq"}
															initial={animation1}
															layoutDependency={layoutDependency}
															layoutId={"dmHPSLCpF-container"}
															nodeId={"dmHPSLCpF"}
															optimized={true}
															rendersWithMotion={true}
															scopeId={"LZvKUrvDA"}
														>
															{_jsx(stdin_default3, {
																suppressHydrationWarning: true,
																height: "100%",
																id: "dmHPSLCpF",
																layoutId: "dmHPSLCpF",
																Np9CObSKS: {
																	borderColor:
																		"var(--token-5bafd284-4248-4179-8fdd-7a454d5f3ef0, rgb(160, 175, 100))",
																	borderStyle: "solid",
																	borderWidth: 1,
																},
																QXHcdXjw7:
																	"3px 4px 0px 0px var(--token-5bafd284-4248-4179-8fdd-7a454d5f3ef0, rgb(160, 175, 100))",
																RQEvdrXW0: QxkZWvI2zfdu0v1MtY,
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: matchVariant("vOlkK4IVV"),
																width: "100%",
																z4hpWgaDr: XxkBqqz4Ufdu0v1MtY,
																zNqg7GDkY:
																	"var(--token-e8cec243-b334-4568-a85b-a75cea534593, rgb(214, 229, 154))",
																...addPropertyOverrides(
																	{
																		bK0E6Ygrl: {
																			variant: matchVariant("zpZ8Hyds8"),
																		},
																		kfh2W1SR5: {
																			variant: matchVariant("zpZ8Hyds8"),
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
												{visible6 !== false && (
													<ComponentViewportProvider
														suppressHydrationWarning={true}
														height={0}
														width={`max((max((min(${componentViewport?.width || "100vw"}, 1460px) - 140px) * 0.5652, 1px) - 40px) / 3, 50px)`}
														{...addPropertyOverrides(
															{
																bK0E6Ygrl: {
																	width: `max(min(${componentViewport?.width || "100vw"}, 1460px) - 40px, 50px)`,
																},
																kfh2W1SR5: {
																	width: `calc(max((max((min(${componentViewport?.width || "100vw"}, 1460px) - 100px) * 0.5652, 1px) - 20px) / 2, 50px) * 2 + 20px)`,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															suppressHydrationWarning={true}
															__perspectiveFX={false}
															__smartComponentFX={true}
															__targetOpacity={1}
															animate={animation7}
															className={"framer-1y7bjja-container"}
															data-framer-appear-id={"1y7bjja"}
															initial={animation1}
															layoutDependency={layoutDependency}
															layoutId={"uiHztwp83-container"}
															nodeId={"uiHztwp83"}
															optimized={true}
															rendersWithMotion={true}
															scopeId={"LZvKUrvDA"}
														>
															{_jsx(stdin_default3, {
																suppressHydrationWarning: true,
																height: "100%",
																id: "uiHztwp83",
																layoutId: "uiHztwp83",
																Np9CObSKS: {
																	borderColor:
																		"var(--token-1155d13b-37e2-47ed-93ce-c08c2cfdd816, rgb(190, 143, 169))",
																	borderStyle: "solid",
																	borderWidth: 1,
																},
																QXHcdXjw7:
																	"3px 4px 0px 0px var(--token-1155d13b-37e2-47ed-93ce-c08c2cfdd816, rgb(190, 143, 169))",
																RQEvdrXW0: mWtmbqNAtfdu0v1MtY,
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: matchVariant("vOlkK4IVV"),
																width: "100%",
																z4hpWgaDr: lNQa0DDFIfdu0v1MtY,
																zNqg7GDkY:
																	"var(--token-d0e4cb96-2373-4292-a52b-0c70e08d9898, rgb(246, 215, 232))",
																...addPropertyOverrides(
																	{
																		bK0E6Ygrl: {
																			variant: matchVariant("zpZ8Hyds8"),
																		},
																		kfh2W1SR5: {
																			variant: matchVariant("zpZ8Hyds8"),
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
											</motion.div>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={90}
								width={componentViewport?.width || "100vw"}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1r8w8lk-container"}
									layoutDependency={layoutDependency}
									layoutId={"r3sI_htcv-container"}
									nodeId={"r3sI_htcv"}
									rendersWithMotion={true}
									scopeId={"LZvKUrvDA"}
								>
									{_jsx(stdin_default2, {
										suppressHydrationWarning: true,
										height: "100%",
										id: "r3sI_htcv",
										layoutId: "r3sI_htcv",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: matchVariant("IUzaZzMmw"),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	".framer-vzx6o.framer-1gx3ele, .framer-vzx6o .framer-1gx3ele { display: block; }",
	".framer-vzx6o.framer-1i63swv { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-vzx6o .framer-14h3b8k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 146px 0px 150px 0px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-i3tt6z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-1pqsmac { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-vzx6o .framer-1jzk0t0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-i4m78n { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 1; }",
	".framer-vzx6o .framer-xemop0, .framer-vzx6o .framer-4dowtn, .framer-vzx6o .framer-1ir8olv, .framer-vzx6o .framer-fa5nr2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-vzx6o .framer-imaiz5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-133zy5k { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-vzx6o .framer-oen83t { flex: none; height: auto; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-vzx6o .framer-15xeqtc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 14px 0px 0px; position: absolute; right: -20px; top: -30px; width: min-content; }",
	".framer-vzx6o .framer-kbctvr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 12px 30px 12px 30px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-vzx6o .framer-1mex38g { align-content: flex-start; align-items: flex-start; display: flex; flex: 1.3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-vzx6o .framer-utlr18 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-jxj3w7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-vzx6o .framer-t5azft { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-vzx6o .framer-js4v7e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-lrvwr5-container, .framer-vzx6o .framer-1qco4zu-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-vzx6o .framer-1wseqrf { display: grid; flex: none; gap: 20px 20px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; overflow: visible; padding: 20px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-vzx6o .framer-1wwrazi-container, .framer-vzx6o .framer-193s4mq-container, .framer-vzx6o .framer-1y7bjja-container { align-self: start; flex: none; height: 100%; justify-self: start; position: relative; width: 100%; }",
	".framer-vzx6o .framer-1r8w8lk-container { bottom: 0px; flex: none; height: 90px; left: 0px; position: absolute; right: 0px; z-index: 1; }",
	".framer-vzx6o.framer-v-1ilxzzf.framer-1i63swv { width: 810px; }",
	".framer-vzx6o.framer-v-1ilxzzf .framer-14h3b8k { padding: 130px 0px 130px 0px; }",
	".framer-vzx6o.framer-v-1ilxzzf .framer-imaiz5 { align-content: flex-start; align-items: flex-start; gap: 40px; }",
	".framer-vzx6o.framer-v-1ilxzzf .framer-1mex38g { gap: 40px; }",
	".framer-vzx6o.framer-v-1ilxzzf .framer-1wseqrf { grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-vzx6o.framer-v-1ilxzzf .framer-1y7bjja-container { grid-column: span 2; }",
	".framer-vzx6o.framer-v-1i8rxy6.framer-1i63swv { width: 390px; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-14h3b8k { padding: 100px 0px 100px 0px; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-i3tt6z { padding: 0px 20px 0px 20px; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-imaiz5 { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 40px; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-133zy5k { flex: none; width: 100%; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-15xeqtc { right: 0px; top: -20px; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-kbctvr { padding: 10px 20px 10px 20px; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-1mex38g { flex: none; gap: 30px; width: 100%; }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-1wseqrf { grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	".framer-vzx6o.framer-v-1i8rxy6 .framer-1y7bjja-container { grid-column: span 1; }",
	...css2,
	...css5,
	...css,
	...css3,
	...css4,
	'.framer-vzx6o[data-border="true"]::after, .framer-vzx6o [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerLZvKUrvDA = withCSS(Component, css6, "framer-vzx6o");
var stdin_default4 = FramerLZvKUrvDA;
FramerLZvKUrvDA.displayName = "Program Detail Section 1 \u2014 Hero";
FramerLZvKUrvDA.defaultProps = {
	height: 603,
	width: 1200,
};
addPropertyControls(FramerLZvKUrvDA, {
	variant: {
		options: ["HN6KdX4Ig", "kfh2W1SR5", "bK0E6Ygrl"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerLZvKUrvDA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...InfoCardFonts,
		...SectionDecorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerLZvKUrvDA.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default3, {}, context),
			forwardLoader(stdin_default2, {}, context),
		]);
	},
};

// virtual:program-detail-section-1-hero
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProgramDetailSection1HeroFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var program_detail_section_1_hero_default = ComponentWithRoot;
export { program_detail_section_1_hero_default as default };


// --- unframer-cms-binding (generated by scripts/bind-cms.mjs) ---
export function __bindCmsFields(values) {
	if ("bw5wYLxeb_QLObxbGfm" in values) bw5wYLxeb_QLObxbGfmfdu0v1MtY = values["bw5wYLxeb_QLObxbGfm"];
	if ("hUvhbUSVS" in values) hUvhbUSVSfdu0v1MtY = values["hUvhbUSVS"];
	if ("K6guXv55O" in values) K6guXv55Ofdu0v1MtY = values["K6guXv55O"];
	if ("HNtd_VJxB" in values) HNtd_VJxBfdu0v1MtY = values["HNtd_VJxB"];
	if ("TsxYJujxI" in values) TsxYJujxIfdu0v1MtY = values["TsxYJujxI"];
	if ("gZLQKE2TD" in values) gZLQKE2TDfdu0v1MtY = values["gZLQKE2TD"];
	if ("BuzbVg2cg" in values) BuzbVg2cgfdu0v1MtY = values["BuzbVg2cg"];
	if ("XxkBqqz4U" in values) XxkBqqz4Ufdu0v1MtY = values["XxkBqqz4U"];
	if ("QxkZWvI2z" in values) QxkZWvI2zfdu0v1MtY = values["QxkZWvI2z"];
	if ("lNQa0DDFI" in values) lNQa0DDFIfdu0v1MtY = values["lNQa0DDFI"];
	if ("mWtmbqNAt" in values) mWtmbqNAtfdu0v1MtY = values["mWtmbqNAt"];
}
export const __cmsFieldIds = ["bw5wYLxeb_QLObxbGfm","hUvhbUSVS","K6guXv55O","HNtd_VJxB","TsxYJujxI","gZLQKE2TD","BuzbVg2cg","XxkBqqz4U","QxkZWvI2z","lNQa0DDFI","mWtmbqNAt"];
