// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-MLB3MC5T.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-AOWK4JFD.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-4XRGEVGL.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-6ONBAXWQ.js";
import {
	className as className8,
	css as css8,
	fonts as fonts8,
} from "./chunks/chunk-EPDNPLDL.js";
import { className, css, fonts } from "./chunks/chunk-RFLCCK3R.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-R5PSICTC.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-FUMATQXC.js";
import { stdin_default } from "./chunks/chunk-DPP5EL47.js";
import "./chunks/chunk-C742CGXR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:program-detail-section-3-mentor
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/AQ3WQim7Me6MWiOU4ihQ/UGMtuaIzqbIOXIW8EE96/ZakYSfiOS.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var PreTitleFonts = getFonts(stdin_default2);
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = ["N6jwWgtMx", "VAkwTBwDd", "euDEQPzxC"];
var serializationHash = "framer-85OzR";
var variantClassNames = {
	euDEQPzxC: "framer-v-y3h29j",
	N6jwWgtMx: "framer-v-s2j3s3",
	VAkwTBwDd: "framer-v-1mn1dk9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var bw5wYLxeb_koQ7t_K7pfdu0v1MtY = void 0;
var bw5wYLxeb_QLObxbGfmfdu0v1MtY = void 0;
var bw5wYLxeb_s9bPlqbuPfdu0v1MtY = void 0;
var bw5wYLxeb_YfmS2tChUfdu0v1MtY = void 0;
var bw5wYLxeb_zGSu5TpRvfdu0v1MtY = void 0;
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition3 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "N6jwWgtMx",
	Phone: "euDEQPzxC",
	Tablet: "VAkwTBwDd",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "N6jwWgtMx",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className9,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "N6jwWgtMx",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className8,
		className2,
		className5,
		className6,
		className4,
		className3,
		className7,
		className,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(bw5wYLxeb_koQ7t_K7pfdu0v1MtY);
	const visible1 = isSet(bw5wYLxeb_QLObxbGfmfdu0v1MtY);
	const visible2 = isSet(bw5wYLxeb_YfmS2tChUfdu0v1MtY);
	const visible3 = isSet(bw5wYLxeb_zGSu5TpRvfdu0v1MtY);
	const router = useRouter();
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-s2j3s3",
							className9,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"N6jwWgtMx"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								euDEQPzxC: {
									"data-framer-name": "Phone",
								},
								VAkwTBwDd: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							suppressHydrationWarning={true}
							className={"framer-112qrm5"}
							data-framer-name={"Mentor"}
							layoutDependency={layoutDependency}
							layoutId={"FDEO362Sq"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1k8iz75"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"xedbZZWUs"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1t9b9jy"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"uAcf5HXlh"}
								>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-15ufaql"}
										data-framer-name={"Left"}
										layoutDependency={layoutDependency}
										layoutId={"mLdjhs1CN"}
									>
										{visible !== false && (
											<Image1
												suppressHydrationWarning={true}
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 550,
													intrinsicWidth: 590,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															0 +
															150 +
															0 +
															0 +
															0 +
															67 +
															0 +
															5,
													),
													pixelHeight: 550,
													pixelWidth: 590,
													sizes: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 180px) / 2.3, 1px)`,
													...toResponsiveImage(bw5wYLxeb_koQ7t_K7pfdu0v1MtY),
												}}
												className={"framer-1c326si"}
												fitImageDimension={"height"}
												layoutDependency={layoutDependency}
												layoutId={"fKXn69NYb"}
												style={{
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
												{...addPropertyOverrides(
													{
														euDEQPzxC: {
															background: {
																alt: "",
																fit: "fill",
																intrinsicHeight: 550,
																intrinsicWidth: 590,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		0 +
																		0 +
																		80 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		5,
																),
																pixelHeight: 550,
																pixelWidth: 590,
																sizes: `calc(min(${componentViewport?.width || "100vw"}, 1460px) - 40px)`,
																...toResponsiveImage(
																	bw5wYLxeb_koQ7t_K7pfdu0v1MtY,
																),
															},
														},
														VAkwTBwDd: {
															background: {
																alt: "",
																fit: "fill",
																intrinsicHeight: 550,
																intrinsicWidth: 590,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		0 +
																		0 +
																		100 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		5,
																),
																pixelHeight: 550,
																pixelWidth: 590,
																sizes: `max((min(${componentViewport?.width || "100vw"}, 1460px) - 110px) / 2.3, 1px)`,
																...toResponsiveImage(
																	bw5wYLxeb_koQ7t_K7pfdu0v1MtY,
																),
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										)}
									</MotionDivWithFX>
									<MotionDivWithFX
										suppressHydrationWarning={true}
										__framer__animate={{
											transition: transition3,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-63nas5"}
										data-framer-name={"Right"}
										layoutDependency={layoutDependency}
										layoutId={"AA3kimpFJ"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-6qog49"}
											data-framer-name={"01"}
											layoutDependency={layoutDependency}
											layoutId={"JslgiIors"}
										>
											{visible1 !== false && (
												<motion.div
													suppressHydrationWarning={true}
													className={"framer-1qh2e0z"}
													data-framer-name={"Title"}
													layoutDependency={layoutDependency}
													layoutId={"apfkmWlDi"}
												>
													<ComponentViewportProvider
														suppressHydrationWarning={true}
														height={34}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															150 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0
														}
														{...addPropertyOverrides(
															{
																euDEQPzxC: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		0 +
																		80 +
																		0 +
																		0 +
																		0 +
																		0 +
																		40 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																},
																VAkwTBwDd: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		0 +
																		100 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															suppressHydrationWarning={true}
															className={"framer-1fqddz8-container"}
															layoutDependency={layoutDependency}
															layoutId={"YV1D1goZ0-container"}
															nodeId={"YV1D1goZ0"}
															rendersWithMotion={true}
															scopeId={"ZakYSfiOS"}
														>
															{_jsx(stdin_default2, {
																suppressHydrationWarning: true,
																height: "100%",
																HJ8LmVVDm:
																	"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
																id: "YV1D1goZ0",
																layoutId: "YV1D1goZ0",
																qzeUwXZ6t:
																	"var(--token-9be2179a-d4c3-4b1c-a57e-66ad0ebb844d, rgb(232, 114, 44))",
																wCKXxEnrH: bw5wYLxeb_s9bPlqbuPfdu0v1MtY,
																width: "100%",
																ZFJwwHvsK:
																	"var(--token-d0e4cb96-2373-4292-a52b-0c70e08d9898, rgb(246, 215, 232))",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
													<RichText
														suppressHydrationWarning={true}
														__fromCanvasComponent={true}
														className={"framer-164sqgb"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"XPfVT1_Lq"}
														style={{
															"--extracted-1of0zx5":
																"var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29))",
														}}
														text={bw5wYLxeb_QLObxbGfmfdu0v1MtY}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h2
																suppressHydrationWarning={true}
																className={"framer-styles-preset-jcbbly"}
																data-styles-preset={"UXoQEMm1m"}
																dir={"auto"}
																style={{
																	"--framer-text-alignment": "start",
																	"--framer-text-color":
																		"var(--extracted-1of0zx5, var(--token-ba50d2e5-600e-4acb-b91c-6cca2f86f1d6, rgb(20, 38, 29)))",
																}}
															>
																{"Mathematics"}
															</motion.h2>
														</React.Fragment>
													</RichText>
												</motion.div>
											)}
											{visible2 !== false && (
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-be56z5"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"ztJaBYxjT"}
													text={bw5wYLxeb_YfmS2tChUfdu0v1MtY}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-7580yq"}
															data-styles-preset={"ESdyUGyJl"}
															dir={"auto"}
															style={{
																"--framer-text-alignment": "start",
															}}
														>{`Nine years as a school math teacher, five at BrightPath. Maya's specialty is the learner who has decided they're "just not a math person" she disagrees, and she's usually right within a month. Her sessions run on questions, not lectures: learners do the talking, she does the steering.`}</motion.p>
													</React.Fragment>
												</RichText>
											)}
										</motion.div>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1fm41jb"}
											data-framer-name={"02"}
											layoutDependency={layoutDependency}
											layoutId={"fuZBJUbf9"}
										>
											{visible3 !== false && (
												<RichText
													suppressHydrationWarning={true}
													__fromCanvasComponent={true}
													className={"framer-131rk4"}
													data-framer-name={"Expertise"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"p0_vVmNRO"}
													style={{
														"--framer-paragraph-spacing": "10px",
													}}
													stylesPresetsClassNames={{
														a: "framer-styles-preset-eke6e",
														h1: "framer-styles-preset-1w1zhlt",
														h2: "framer-styles-preset-jcbbly",
														h3: "framer-styles-preset-1mec8v8",
														h4: "framer-styles-preset-8gnvci",
														h5: "framer-styles-preset-1limcq0",
														h6: "framer-styles-preset-1fxd4ok",
														p: "framer-styles-preset-7580yq",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													{bw5wYLxeb_zGSu5TpRvfdu0v1MtY}
												</RichText>
											)}
										</motion.div>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1r99eqh"}
											data-framer-name={"03"}
											layoutDependency={layoutDependency}
											layoutId={"I0buOitrX"}
										>
											<ResolveLinks
												suppressHydrationWarning={true}
												links={[
													{
														href: {
															webPageId: "peTwLqil9",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "peTwLqil9",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "peTwLqil9",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks) => (
													<ComponentViewportProvider
														suppressHydrationWarning={true}
														height={54}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															150 +
															0 +
															0 +
															0 +
															0 +
															0 +
															60 +
															20 +
															0
														}
														{...addPropertyOverrides(
															{
																euDEQPzxC: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		0 +
																		80 +
																		0 +
																		0 +
																		0 +
																		0 +
																		40 +
																		0 +
																		60 +
																		20 +
																		0,
																},
																VAkwTBwDd: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		0 +
																		100 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		60 +
																		20 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															suppressHydrationWarning={true}
															className={"framer-la9rq8-container"}
															layoutDependency={layoutDependency}
															layoutId={"MNFzAchKh-container"}
															nodeId={"MNFzAchKh"}
															rendersWithMotion={true}
															scopeId={"ZakYSfiOS"}
														>
															{_jsx(stdin_default, {
																suppressHydrationWarning: true,
																height: "100%",
																id: "MNFzAchKh",
																Kiib3s3Y3: "Try a free session",
																layoutId: "MNFzAchKh",
																toG7h_P8o: resolvedLinks[0],
																variant: matchVariant("EUoTryFDz"),
																width: "100%",
																Y5KJgXrXk: false,
																...addPropertyOverrides(
																	{
																		euDEQPzxC: {
																			toG7h_P8o: resolvedLinks[2],
																			variant: matchVariant("ltttFCNrV"),
																		},
																		VAkwTBwDd: {
																			toG7h_P8o: resolvedLinks[1],
																			variant: matchVariant("ltttFCNrV"),
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										</motion.div>
									</MotionDivWithFX>
								</motion.div>
							</motion.div>
						</motion.section>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css9 = [
	".framer-85OzR.framer-hfzpyj, .framer-85OzR .framer-hfzpyj { display: block; }",
	".framer-85OzR.framer-s2j3s3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1200px; }",
	".framer-85OzR .framer-112qrm5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 150px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-85OzR .framer-1k8iz75 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; max-width: 1460px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-85OzR .framer-1t9b9jy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-85OzR .framer-15ufaql { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-85OzR .framer-1c326si { flex: none; height: auto; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-85OzR .framer-63nas5 { align-content: center; align-items: center; display: flex; flex: 1.3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-85OzR .framer-6qog49, .framer-85OzR .framer-1fm41jb { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-85OzR .framer-1qh2e0z { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-85OzR .framer-1fqddz8-container, .framer-85OzR .framer-la9rq8-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-85OzR .framer-164sqgb, .framer-85OzR .framer-131rk4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-85OzR .framer-be56z5 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-85OzR .framer-1r99eqh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-85OzR.framer-v-1mn1dk9.framer-s2j3s3 { width: 810px; }",
	".framer-85OzR.framer-v-1mn1dk9 .framer-112qrm5 { padding: 100px 0px 0px 0px; }",
	".framer-85OzR.framer-v-1mn1dk9 .framer-1t9b9jy { align-content: flex-start; align-items: flex-start; gap: 50px; }",
	".framer-85OzR.framer-v-y3h29j.framer-s2j3s3 { width: 390px; }",
	".framer-85OzR.framer-v-y3h29j .framer-112qrm5 { padding: 80px 0px 0px 0px; }",
	".framer-85OzR.framer-v-y3h29j .framer-1k8iz75 { padding: 0px 20px 0px 20px; }",
	".framer-85OzR.framer-v-y3h29j .framer-1t9b9jy { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 40px; }",
	".framer-85OzR.framer-v-y3h29j .framer-15ufaql, .framer-85OzR.framer-v-y3h29j .framer-63nas5 { flex: none; width: 100%; }",
	...css8,
	...css2,
	...css5,
	...css6,
	...css4,
	...css3,
	...css7,
	...css,
];
var FramerZakYSfiOS = withCSS(Component, css9, "framer-85OzR");
var stdin_default3 = FramerZakYSfiOS;
FramerZakYSfiOS.displayName = "Program Detail Section 3 \u2014 Mentor";
FramerZakYSfiOS.defaultProps = {
	height: 200,
	width: 200,
};
addPropertyControls(FramerZakYSfiOS, {
	variant: {
		options: ["N6jwWgtMx", "VAkwTBwDd", "euDEQPzxC"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerZakYSfiOS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PreTitleFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerZakYSfiOS.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:program-detail-section-3-mentor
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProgramDetailSection3MentorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var program_detail_section_3_mentor_default = ComponentWithRoot;
export { program_detail_section_3_mentor_default as default };


// --- unframer-cms-binding (generated by scripts/bind-cms.mjs) ---
export function __bindCmsFields(values) {
	if ("bw5wYLxeb_koQ7t_K7p" in values) bw5wYLxeb_koQ7t_K7pfdu0v1MtY = values["bw5wYLxeb_koQ7t_K7p"];
	if ("bw5wYLxeb_QLObxbGfm" in values) bw5wYLxeb_QLObxbGfmfdu0v1MtY = values["bw5wYLxeb_QLObxbGfm"];
	if ("bw5wYLxeb_s9bPlqbuP" in values) bw5wYLxeb_s9bPlqbuPfdu0v1MtY = values["bw5wYLxeb_s9bPlqbuP"];
	if ("bw5wYLxeb_YfmS2tChU" in values) bw5wYLxeb_YfmS2tChUfdu0v1MtY = values["bw5wYLxeb_YfmS2tChU"];
	if ("bw5wYLxeb_zGSu5TpRv" in values) bw5wYLxeb_zGSu5TpRvfdu0v1MtY = values["bw5wYLxeb_zGSu5TpRv"];
}
export const __cmsFieldIds = ["bw5wYLxeb_koQ7t_K7p","bw5wYLxeb_QLObxbGfm","bw5wYLxeb_s9bPlqbuP","bw5wYLxeb_YfmS2tChU","bw5wYLxeb_zGSu5TpRv"];
