// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * time?: string // Time
 * onwxrLBNwLSCHange?: any // onwxrLBNwLSCHange
 * title?: string // Title
 * onmVX3_SfbpChange?: any // onmVX3_SfbpChange
 * info?: string // Info
 * onbbnFVDcH_Change?: any // onbbnFVDcH_Change
 * topicBGColor?: string // Topic BG Color
 * topicBorder?: any // Topic Border
 * topicShadow?: any // Topic Shadow
}} Props

 */
import { stdin_default } from "./chunks/chunk-7H4S3KC5.js";
import "./chunks/chunk-R5PSICTC.js";
import "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:session-card
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SessionCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var session_card_default = ComponentWithRoot;
export { session_card_default as default };
