// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 136c9ca46c906301 "Brightpath (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title01?: string // Title 01
 * onOwvx2GltVCHange?: any // onOwvx2GltVCHange
 * title02?: string // Title 02
 * ondKCN05QzmChange?: any // ondKCN05QzmChange
 * title03?: string // Title 03
 * onh3NwTAI1yChange?: any // onh3NwTAI1yChange
 * title04?: string // Title 04
 * onNUGINVJk_Change?: any // onNUGINVJk_Change
 * title05?: string // Title 05
 * onCQWGP8kGtChange?: any // onCQWGP8kGtChange
}} Props

 */
import { stdin_default } from "./chunks/chunk-QAVJZWO2.js";
import "./chunks/chunk-UR7P3ULX.js";
import "./chunks/chunk-3RSWXIIC.js";
import { routes } from "./chunks/chunk-IWD22LQP.js";

// virtual:team-expertise
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamExpertiseFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"136c9ca46c906301abf35ab4efae378632bbed88a714a32081c423300c4c6247"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_expertise_default = ComponentWithRoot;
export { team_expertise_default as default };
