/**
 * Locally authored CMS content, layered over `lib/cms.json`.
 *
 * `cms.json` is a snapshot regenerated by `pnpm cms`, so editing it directly
 * loses the edit on the next export -- the same reason artwork is overridden in
 * `app/globals.css` rather than in `framer/`. This is that idea for text: the
 * snapshot stays exactly as Framer produced it, and everything written here is
 * applied on top of it when `lib/cms.ts` builds the exported collections.
 *
 * The right long-term home for any of this is the Framer CMS itself. Move an
 * entry there, run `pnpm cms`, and delete it from this file.
 *
 * ---
 *
 * Field ids, not field names, are what reach the generated components: unframer
 * emits each binding as a module-level `var <fieldId><pageId>`, and
 * `__bindCmsFields` writes to those. The table below is the mapping for the
 * Program collection, read out of `cms.json` and checked against the ids the
 * generated files actually bind -- every id here appears in a
 * `framer/program-detail-section-*.jsx`. `lib/cms.ts` writes both the id and the
 * human name so server components (`generateMetadata`) and the rendered page
 * cannot disagree.
 */
export const PROGRAM_FIELD_IDS = {
    Title: 'hUvhbUSVS',
    Info: 'EnXNFcio9',
    'Level Tag': 'HNtd_VJxB',
    Description: 'TsxYJujxI',
    'Label 01': 'BuzbVg2cg',
    'Value 01': 'gZLQKE2TD',
    'Label 02': 'QxkZWvI2z',
    'Value 02': 'XxkBqqz4U',
    'Label 03': 'mWtmbqNAt',
    'Value 03': 'lNQa0DDFI',
    'Syllabus Part 01': 'AlYJU3rfd',
    'Syllabus Part 02': 'Atet3qL3U',
    'Syllabus Part 03': 'WKiK9v9LC',
    'Syllabus Part 04': 'B3GrEvcRf',
    'Session Type 01': 'o2t1Enj0m',
    'Session Type 02': 'ym1ibWGrd',
    'Session Type 03': 'DoMyhitd7',
    FAQs: 'dhFBoRH5X',
} as const

export type ProgramFieldName = keyof typeof PROGRAM_FIELD_IDS

/**
 * The Program collection's link to a Mentor. The export flattens the linked item
 * alongside it as `<linkFieldId>_<mentorFieldId>`, which is how the mentor block
 * on a programme page gets its values -- so repointing the link means rewriting
 * that whole prefixed set, not just this one key.
 */
export const PROGRAM_MENTOR_FIELD_ID = 'bw5wYLxeb'

export type ProgramOverride = {
    /** Plain values, replacing the snapshot's outright. */
    fields?: Partial<Record<ProgramFieldName, unknown>>
    /**
     * Patches for fields whose value is a component embed, keyed by field name
     * and indexed by position in the embed list. Each patch is merged over that
     * embed's existing `props`, so icons and `--token-` colours stay whatever
     * the snapshot says and keep tracking Framer. Only text needs restating.
     *
     * Merging also preserves the empty-string props the cards rely on:
     * `listItem05: ''` means "hide this row", and dropping the key entirely
     * would show a placeholder instead.
     */
    embeds?: Partial<Record<ProgramFieldName, Array<Record<string, unknown>>>>
    /** Mentor slug to show in the programme's mentor section. */
    mentor?: string
}

export const PROGRAM_OVERRIDES: Record<string, ProgramOverride> = {
    /**
     * Repurposed from the template's Mathematics programme, so the slug (and
     * therefore the URL) is still `mathematics` while everything on the page is
     * about Scratch. Renaming the slug is a Framer CMS change -- it would move
     * the route to /program/scratch-programming and break any existing link.
     */
    mathematics: {
        fields: {
            Title: 'Scratch Programming',
            Info: 'Build games, animations and stories in Scratch. Learners drag blocks instead of typing syntax, so the ideas behind programming land before the keyboard gets in the way.',
            Description:
                'Every project runs the moment it is built, so a learner watches loops, conditionals and variables work rather than reading about them. Those habits transfer straight to Python later.',
            'Label 01': 'Project tracks',
            'Value 01': '04',
        },
        embeds: {
            'Syllabus Part 01': [
                {
                    topic: 'Foundations',
                    subject: 'Sprites & motion',
                    listItem01: 'Stage, sprites, costumes',
                    listItem02: 'Move, turn, glide',
                    listItem03: 'x and y on the stage',
                    listItem04: 'A first animation',
                },
            ],
            'Syllabus Part 02': [
                {
                    topic: 'Core',
                    subject: 'Loops & events',
                    listItem01: 'Repeat and forever',
                    listItem02: 'When-clicked events',
                    listItem03: 'Broadcast messages',
                    listItem04: 'Sound and music blocks',
                },
            ],
            'Syllabus Part 03': [
                {
                    topic: 'Advanced',
                    subject: 'Logic & variables',
                    listItem01: 'If / else branching',
                    listItem02: 'Variables and scores',
                    listItem03: 'Lists and data',
                    listItem04: 'Sensing and collisions',
                },
            ],
            'Syllabus Part 04': [
                {
                    topic: 'Mastery',
                    subject: 'Games & sharing',
                    listItem01: 'Clones and levels',
                    listItem02: 'Custom blocks',
                    listItem03: 'Debugging a project',
                    listItem04: 'Publishing to a studio',
                },
            ],
            'Session Type 01': [
                {
                    description:
                        'A dedicated mentor at your own pace. Best for a learner with a game idea they want to finish properly.',
                },
            ],
            'Session Type 02': [
                {
                    description:
                        "Max four learners at the same level. They remix and build on each other's projects, which is how Scratch is meant to be used.",
                },
            ],
            FAQs: [
                {
                    _01Question: 'Does my child need to be able to type?',
                    _01Answer:
                        'No. Scratch is drag-and-drop, so nothing has to be typed or spelled correctly for a project to run. Comfortable reading helps, and most learners start from around age eight.',
                    _02Question: 'Is Scratch real programming?',
                    _02Answer:
                        'Yes. Loops, conditionals, variables, events and debugging are all there — the blocks only remove the typing. Those ideas carry over directly when your child moves on to Python.',
                    _03Question: 'What do we need at home?',
                    _03Answer:
                        'A laptop or desktop with a browser. Scratch is free at scratch.mit.edu, and we can set up the offline editor where the connection is unreliable.',
                    _04Question: 'What comes after Scratch?',
                    _04Answer:
                        'Text-based coding, once projects outgrow the blocks. We use something your child already built as the bridge and rebuild it in Python, so it never feels like starting over.',
                },
            ],
        },
        // The template paired this programme with the maths mentor, whose bio is
        // explicitly about maths teaching. Alex Rivera is the existing coding
        // mentor, so the section reads correctly with no invented content.
        mentor: 'alex-rivera',
    },
}
