/**
 * unframer stubs every CMS binding out as a module-level `var X = void 0;`, so
 * the exported detail pages render their real Framer design with all CMS values
 * blank. The values are never exposed as props -- the only prop these components
 * take is `variant` -- so there is no supported way to feed them.
 *
 * They are, however, plain module-scoped `var`s, which can be reassigned from
 * inside the same module. This script appends a `__bindCmsFields(values)` export
 * to each affected file that assigns them by CMS field id. Callers set the
 * fields immediately before rendering the component.
 *
 * Re-run after every `npm run framer`; it is wired into that script.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const DIR = new URL('../framer/', import.meta.url).pathname
const MARKER = '// --- unframer-cms-binding (generated by scripts/bind-cms.mjs) ---'
// CMS detail page ids: mentor, program, legal, plus the listing pages.
const PAGE_IDS = ['K3J5jRO36', 'fdu0v1MtY', 'FnxmyuZM_', 'JtLwS9TeY', 'Zb8AJO2M5']
const pattern = new RegExp(`^var ([A-Za-z0-9_]+)(${PAGE_IDS.join('|')}) = void 0;$`, 'gm')

let patched = 0
for (const file of readdirSync(DIR).filter((f) => f.endsWith('.jsx'))) {
    const path = join(DIR, file)
    let src = readFileSync(path, 'utf8')
    if (src.includes(MARKER)) continue

    const bindings = [...src.matchAll(pattern)].map(([, fieldId, pageId]) => ({
        fieldId,
        varName: fieldId + pageId,
    }))
    if (bindings.length === 0) continue

    const assignments = bindings
        .map((b) => `\tif (${JSON.stringify(b.fieldId)} in values) ${b.varName} = values[${JSON.stringify(b.fieldId)}];`)
        .join('\n')

    src += `\n\n${MARKER}\nexport function __bindCmsFields(values) {\n${assignments}\n}\nexport const __cmsFieldIds = ${JSON.stringify(bindings.map((b) => b.fieldId))};\n`
    writeFileSync(path, src)
    patched++
    console.log(`bound ${bindings.length} field(s) in ${file}`)
}
console.log(patched ? `\npatched ${patched} file(s)` : 'nothing to patch')
